### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'undefined'

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#1005]
https://sentry.io/cph/server/issues/604216169/

```
ValueError: invalid literal for int() with base 10: 'undefined'
(4 additional frame(s) were not displayed)
...
  File "virtool/http/proxy.py", line 69, in middleware
    return await handler(req)
  File "virtool/app_auth.py", line 100, in middleware
    response = await handler(req)
  File "virtool/http/routes.py", line 81, in wrapped
    return await handler(req)
  File "virtool/api/users.py", line 36, in find
    projection=virtool.db.users.PROJECTION
  File "virtool/api/utils.py", line 220, in paginate
    page = int(url_query.get("page", 1))

Error handling request
```

**Comment by igboyes** [comment]
This is caused by passing `page=undefined` in the URL query.
- make sure `undefined` isn't passed in query (@Miminko)
- make API handle bad `page` value gracefully (@igboyes)

**Comment by Miminko** [comment]
I think this error was caused while I was implementing the scrolling list for the reference users modal, and shouldn't occur after the changes were merged, but I put in a couple if statements just in case in the newest PR.

**Comment by igboyes** [comment]
Excellent. This shouldn't happen ever again then!
