### ISSUE TITLE
Upload item ordering

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#1024]
The uploads are sorted by progress. During the upload of multiple files, this often results in the upload items rapidly reordering many times.

Sort more intelligently to prevent this ugly visual effect. Uploads with `progress > 0` should always be at the top.

**Comment by Miminko** [comment]
So instead of sorting by progress value, it should instead have all non-zero progress entries above all zero progress entries, regardless of their relative non-zero progress values to keep the list order relatively fixed?

**Comment by igboyes** [comment]
Yes.
