### ISSUE TITLE
Analysis search bar

### ISSUE THREAD

**Issue by Miminko** [virtool/virtool#1034]
Currently the search bar in the analyses list view and job list view is non-functional.
Should the analysis toolbar enable filtering of analyses?
If so, should the search be based on index names rather than the analysis entry name? (since there are only two choices: `PathoscopeBowtie` or `NuVs`)

**Comment by igboyes** [comment]
Yes, this should be enabled. It will require work on the backend.

I am busy fixing myriad issues related to migrating v2 databases to v3. I can deal with the API changes after that.

**Comment by igboyes** [comment]
I've merged changes into `beta.2` that allow searching and pagination of analyses. They are searchable by `user.id` and `reference.name`. Just use the usual `?term=` query parameter scheme.

Not in API docs yet.
