### ISSUE TITLE
Sample rights cannot be edited by Admin

### ISSUE THREAD

**Issue by Miminko** [virtool/virtool#1036]
Currently, sample rights cannot be edited by administrators if they are not the owner of the sample.
A panel stating "Not allowed" is displayed instead.

**Comment by igboyes** [comment]
Based on my code, the API call should succeed for admins whether they are owners or not.

Is this just a UI issue?

**Comment by Miminko** [comment]
Sorry, I should have specified that its purely a UI issue.

The function in `samples/components/Rights.js` currently doesn't check administrator status:
```
    isOwnerOrAdministrator = () => (
        includes(this.props.groups, this.props.group) || this.props.accountId === this.props.ownerId
    );
```

**Comment by igboyes** [comment]
Thanks. Assigned to you.
