### ISSUE TITLE
Invalid input error message when editing sequence segment

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#1060]
![image](https://user-images.githubusercontent.com/5943558/43212808-da5eb04e-8fe9-11e8-858c-e8777bf8747a.png)

- only occuring in some sequences
- sequences were created before the schema update?
- sequences are in default isolate?

Not sure if this is a back- or front-end issue.

**Comment by Miminko** [comment]
I think this is a UI issue for an unhandled response error:
```
errors: {host: ["null value not allowed"]}
id: "invalid_input"
message: "Invalid input"
```
Should the `Host` field be required?

**Comment by igboyes** [comment]
`host` has to either a string or not in the payload at all.
