### ISSUE TITLE
Weird rendering of job detail in error state

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#1127]
Similar to #1123 

![image](https://user-images.githubusercontent.com/5943558/44922494-543ebf80-acfa-11e8-87bd-cf197b5d2697.png)

**Comment by Miminko** [comment]
This should be fixed in #1126 
Did you mean to close that PR?

**Comment by igboyes** [comment]
Oh sorry. I had mental lapse. I haven't re-run webpack since the merge...
