### ISSUE TITLE
Write reference.json.gz during index build

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#1214]
- [ ] Add a _Build JSON_ (`build_json`) step to the `BuildIndex` job that creates a `reference.json.gz` file in the index directory:`<data_path>/references/:ref_id/:index_id`.

- [ ] See `virtool.reference.db.export` and `virtool.downloads.api.download_reference` for on-the-fly reference exporting currently works

This will happen for all new index builds. Active indexes (most recent for a reference) without `json.gz` files will have them generated in a task. See #1148.

- [ ] Share code for creating `json.gz` file with that used in the task described in #1148.

- [ ] Set `has_json` to `False` when build starts and set it to `True` when build is complete

**Comment by tianshengsui** [comment]
> * [ ]  Add a _Build JSON_ (`build_json`) step to the `BuildIndex` job that creates a `reference.json.gz` file in the index directory:`<data_path>/references/:ref_id/:index_id`.
> * [ ]  See `virtool.reference.db.export` and `virtool.downloads.api.download_reference` for on-the-fly reference exporting currently works
> 
> This will happen for all new index builds. Active indexes (most recent for a reference) without `json.gz` files will have them generated in a task. See #1148.
> 
> * [ ]  Share code for creating `json.gz` file with that used in the task described in #1148.
> * [ ]  Set `has_json` to `False` when build starts and set it to `True` when build is complete

Can I put `build_json` step after `upload` step? 

The index directory is created at `upload` step, so if `build_json` step execute first, it will cause a `No such file or directory` error unless I create a directory in `build_json` step as wll.

What do you think?

**Comment by igboyes** [comment]
Sounds good!
