### ISSUE TITLE
NuVs BLAST run stalled

### ISSUE THREAD

**Issue by tranlt** [virtool/virtool#1486]
example sample: 19SP092 NuVs contig 86 blast in progress - last checked a month ago. refreshing does not solve the issue.

**Comment by igboyes** [comment]
![image](https://user-images.githubusercontent.com/5943558/66344455-cec90e00-e902-11e9-9815-31001407d8d3.png)

BLAST is constantly in progress. Request NCBI cannot be found.
- [ ] show error when RID not found
- [ ] allow force retry of running BLAST

**Comment by tranlt** [comment]
not sure if this issue has been looked at yet but found another sample (17TFP138) where many of the contigs are stuck in the blast in process stage and say: last checked 3 months ago. checking again in 3 months

**Comment by igboyes** [comment]
No. Sorry Lan this is still in the queue.
