### ISSUE TITLE
Genbank sequence fetched from NCBI has name/definition truncated if it spans multiple lines

### ISSUE THREAD

**Issue by peterk87** [virtool/virtool#1548]
Some sequences have long names/definitions that may span multiple lines (e.g. https://www.ncbi.nlm.nih.gov/nuccore/FJ175661.1). Currently the name is truncated since the definition is expected to be present on a single line. 

Potential solution may be to use Biopython for parsing Genbank format.

Also, it would be nice to extract all available metadata for a sequence along with the host (isolate, isolation_source, collection_date, note, subtype, serotype, etc) as well as any annotations.

**Comment by igboyes** [comment]
Thanks for documenting this issue. I can deal with this bug pretty quickly.

Although it would make parsing Genbank data and other file formats easier, Biopython is a big dependency to add to the application bundle. I will check what the overall impact is of including it.

I've created another issue about including all metadata in the sequence autofill (#1550). Displaying this data cleanly will require some thought.

**Comment by peterk87** [comment]
The only dependency of BioPython is NumPy which is already being used by Virtool. The wheel file of BioPython v1.75 is only 2.3 MB, which hopefully wouldn't have too much of an impact (https://pypi.org/project/biopython/#files). There are a number of optional dependencies and a lot of bells and whistles that might be nice, but likely not gonna need em.

I've found BioPython's SeqRecord objects to be very convenient, but they can be rather heavy weight and slow when working with a lot of sequences in a basic format. As an alternative BioPython provides a [SimpleFastaParser](https://github.com/biopython/biopython/blob/af73d7e06397c2ce1a9507ea176b3712dd6f0604/Bio/SeqIO/FastaIO.py#L27) that works great for larger fasta files.
