### ISSUE TITLE
Suggestion: File place holder

### ISSUE THREAD

**Issue by ron-reade** [virtool/virtool#1580]
When flipping back between the analysis file, and back to the sample list, it would be real nice if the program remembered where you were last in the sample list… it is really tedious to scroll down the list between each sample in order to get to the next sample to look at. I currently have 190 samples in my Virtool analyzed files and  I am in the process of adding more.

**Comment by igboyes** [comment]
We have prioritized a switch to pagination instead of infinite scroll. Remembering the previous position will be included in this.
