### ISSUE TITLE
Running batch jobs for an analysis - cannot choose samples

### ISSUE THREAD

**Issue by tranlt** [virtool/virtool#1584]
Tried running pathoscope as a batch job for several newly created samples. When the analyze screen tab was opened (from the green tab to the right of the sample name field on the samples page) the samples field is grayed out so one cannot choose the desired parameters for a specific sample.

**Comment by igboyes** [comment]
You have to select your samples to analyze using the checkboxes in the sample list. Then click the green analyze button. The greyed out samples field just shows which samples will be analyzed. This should probably be clearer.

**Comment by tranlt** [comment]
Hello,

Thank you for the clarification. My apologies as perhaps I was not clear myself in communicating what I was trying to do. I selected a group of samples with different hosts hoping that I could batch run pathoscope for all of the samples but also select the host subtraction genome for each sample from the quick analyze screen. I now realize it is not possible to do this, at least for now. Thank you.

**Comment by igboyes** [comment]
The quick analysis will use the sample's default subtraction.

I can think about adding subtraction selection for each analysis in the bulk analysis creator, but it will result in quite a complicated form. Do you think this is necessary?

**Comment by tranlt** [comment]
Hello,

I do not think that would be necessary as one could select samples with the same host beforehand. Thank you for the clarification.
