### ISSUE TITLE
NuVs blast indicating "no name" for some contig hits

### ISSUE THREAD

**Issue by tranlt** [virtool/virtool#1648]
Wondering why NuVs blast results sometimes shows "no name" under the name field but shows values for other fields ? This happens for some contigs but when that contig is blasted in NCBI there is a name to the hit.

**Comment by igboyes** [comment]
Can you give me a specific example for this?

**Comment by ron-reade** [comment]
I have experienced this as well, at least the "No Name" part...have yet to blast the sequence that I got to see if NCBI comes up with something.

**Comment by igboyes** [comment]
Thanks guys. I have reproduced this in testing and will fix it ASAP.

**Comment by igboyes** [comment]
I have looked into this and it is a problem with the results from NCBI.

When Virtool fetches the BLAST result from NCBI, sometimes the accession and name information is missing even though it is part of the result. I have put in a ticket with them to address this. If they are not able to resolve the issue, there are avenues for me to implement a rough fix.

For now, you can manually BLAST the contigs by downloading them and submitting them at NCBI manually. You can also *Retry* the BLAST. The data is inconsistently missing from the result. so retrying the BLAST multiple times will eventually produce a complete result.

**Comment by igboyes** [comment]
NCBI says this should be fixed on their end now. Please re-open the issue if you notice the problem again on future BLAST searches.
