### ISSUE TITLE
Fix snapshot tests involving times

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#1655]
Snapshot tests for `RelativeTime` components need to have a static time to prevent tests from failing every few days as _3 days ago_ moves to _4 days ago_.

I would suggest looking into mocking `Date.now()` to fix this issue. You will have to return an arbitrary time that does not change between test runs.

[`Date.now()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now)

#### Example Snapshot Failure
```
- Expected
861 | + Received
862 |  
863 | Object {
864 | "time": "2020-01-10T12:21:00.000000Z",
865 | -   "timeString": "3 days ago",
866 | +   "timeString": "4 days ago",
867 | }
868 |  
869 | 23 \|         const wrapper = shallow(<RelativeTime {...props} />);
870 | 24 \|         wrapper.setProps({ ...props, time: "2020-01-10T12:21:00.000000Z" });
871 | > 25 \|         expect(wrapper.state()).toEqual({
872 | \|                                 ^
873 | 26 \|             time: "2020-01-10T12:21:00.000000Z",
874 | 27 \|             timeString: "3 days ago"
875 | 28 \|         });
876
```

**Comment by MikeERott** [comment]
Hard at work today I see.

Thanks


Mike Rott
CFIA/ACIA



-------- Original message --------
