### ISSUE TITLE
NuVs post-assembly mapping

### ISSUE THREAD

**Issue by ron-reade** [virtool/virtool#1663]
As I am starting to use the NuVs part of virtool a little more, it has occurred to me that having some sort of indication of median depth for the contig constructed would be super useful information to have.
Thanks

**Comment by igboyes** [comment]
This may be a surprise, but adding this feature would entail a lot of work and would add a significant amount of time to the analysis process.

I have tagged @MikeERott here to see if he thinks there is value in this. It would be good if you could provide some more justification @ron-reade.

Thanks.

**Comment by ron-reade** [comment]
Hi Guys,
So I didn’t realize that this would be a huge deal when I made the suggestion as I assumed it was already calculating this kind of information behind the scenes and just not showing it. Having said that I am of the opinion that this might be worth looking into. The reason I am interested in this information is that it will help validate the information I am getting out of the NuVs data. If I don’t know what kind of coverage I have for any particular sequence it is really hard ascertain if the sequence in question really exists in the “plant” that was sequenced. I have seen this multiple times, where it will pull up a virus (say ACLSV), but in that same analysis under Pathoscope it has ACLSV at 0 median depth, low weight and coverage. Even this is hard to access what it means, did it just cobble together a section of ACLSV from the cross-contamination data that is prevalent in NGS sequencing, or is this a new closely related virus that just doesn’t match well to what is in the virtool database? If I could see even an estimate of coverage I would know right away if it was worth pursuing… median depth of 2…not worth my time, median depth of 200+… worth looking further into. This problem becomes much more complicated when there is nothing in Pathoscope to look at for guidance as in the example above. Also median depth gives me an idea of the prevalence of this sequence in the original sample, so if based on the sequence obtained, I may want to design a strategy to screen for the virus in question, however the strategy that I might employ would potentially be very different if I knew I was looking for something at a very low level versus something that is fairly abundant.

**Comment by MikeERott** [comment]
Hi Ron,
I can see you point, but it would be a lot of work to add, and I'm not sure if it would an effective use of time/resources. I tend to approach it differently. First of all, do I have enough NGS data from the sample that I am confident that a low titre virus would be detection? Do I have enough reads, good reads?  To answer that question, you should be confident in you methods. The longer the contig in NuVs, somewhat suggests degree of presence. With that in place, a new hit is usually fairly obvious, especially if you get multiple virus protein ORFs on a contig. It you are getting a lot of smaller contigs, but there are different contigs matching to different viral proteins of a related virus, that is also a good indication. Lots or short contigs only matching a replicase is not good. If I think I have something interesting, I export it for further analysis using CLC, which is better suited for this. You could also export the contig sequence and enter it into an new user database and use Pathoscope to map to it, but personally I use CLC or another program first to help  put it together.  Doing this will involve multiple rounds of map reading in CLC. Once done, you can  bring it back into Virtool as described above and remap.
