### ISSUE TITLE
Pathoscope subtraction bug

### ISSUE THREAD

**Issue by tranlt** [virtool/virtool#1735]
Noticed that when pathoscope is re-run using a new host subtraction, the host used does not show up in the % mapped box (only the original host used). Would it be useful to have this changed? At first glance it is not clear what host was used unless you go back to check the main sample information screen. Thank you.

**Comment by igboyes** [comment]
This is a bug. Thanks Lan.

**Comment by tranlt** [comment]
Further to this, is there any difference between using different host subtractions? I have run several pathoscope analyses for a sample using different hosts for and have not seen any numerical changes. Thank you.

**Comment by igboyes** [comment]
Will be fixed in next update.
