### ISSUE TITLE
NuV Error

### ISSUE THREAD

**Issue by jp15nw** [virtool/virtool#1828]
When I run a new NuV analysis, I keep getting an error and it stops running. It always happens at the same point (about ¾ way through the job) and it happens with all the samples. I was able to run the analysis before but had to remove some due to storage space. Now that I need to run it again, it doesn't work. I have tried different internet browsers, trying a new connection, and restarting the computer but it still isn't working. I am using version 3.9.6
Any suggestions for what to try next?

**Comment by igboyes** [comment]
Thanks for reporting this. Please post the error here.

**Comment by jp15nw** [comment]
When I click on the job, this is the error message that is at the bottom of the screen. 
Traceback (most recent call last):
File "/drone/src/virtool/jobs/job.py", line 166, in run
File "/drone/src/virtool/jobs/nuvs.py", line 149, in assemble
File "/drone/src/virtool/jobs/job.py", line 261, in run_subprocess
SubprocessError: Command failed: spades.py -t 7 -m 16 -s data/samples/0vdl8wop/analysis/eh1pfv4y/unmapped_hosts.fq -o /tmp/tmpp07xea_t -k 21,33,55,75. Check job log

**Comment by igboyes** [comment]
Go to the job detail view and note the job's ID at the end of the URL (eg. `http://localhost:9950/jobs/qlw5a422` has the ID `qlw5a422`)

Upload the log file found at `data/logs/jobs/<job id>`.

**Comment by jp15nw** [comment]
I have the job ID but I am not sure how to find the job file. Is it a URL?

**Comment by igboyes** [comment]
It is a text file in your Virtool data path.

Making these logs accessbile from the browser is on the todo list!

**Comment by jp15nw** [comment]
How do I get access to the data path? I am still a beginner in command line

**Comment by igboyes** [comment]
You can use the graphical file manager.

1. Move to Virtool install directory. A folder called `data` was created there when you first ran Virtool.
2. Decend through data > logs > jobs
3. Copy file `qlw5a422` somewhere and upload to GitHub or just drag it directly into the browser

**Comment by jp15nw** [comment]
[Log File - lkjrxa8j - Failed NuV.txt](https://github.com/virtool/virtool/files/4531380/Log.File.-.lkjrxa8j.-.Failed.NuV.txt)

**Comment by igboyes** [comment]
The assembly step (using SPAdes) is running out of memory (RAM). I'm not sure why this would be happening when you were able to run NuVs before.

How much memory is available on your machine?

**Comment by jp15nw** [comment]
$ cat /proc/meminfo
MemFree: 47533436 kB

I knew I was running low on memory, but I thought this would be enough to run one analysis

**Comment by igboyes** [comment]
It should be enough. The jobs have lower memory limits configured by default. The job is running up against this limit.

The easiest way to change this is to edit the `config.json` file in your install directory. Look at the [documentation section on configuring resources](https://www.virtool.ca/docs/manual/gs_configuration/#resources). You'll have to increase the instance limits (`proc`, `limit`) and the large job limits (`lg_proc`, `lg_mem`). Look at the **JSON** example for what your edit should look like.

For `proc`, I would suggest setting it to `n - 2` where `n` is the system processor count.

For `mem`, I would suggest setting around `46` (GB) for your system to leave some memory for other processes.

For `lg_proc`, I would suggest `(n - 2) / 2` so you can run two jobs at the same time.

For `lg_mem`, I would suggest `23`. Again, so you can run two jobs.

What kind of extraction are you running? If it is total RNA, the assemblies will generally use more RAM and you may have to set the large jobs to use the entire instance RAM.

**Comment by jp15nw** [comment]
It is total RNA so I would need to set the mem to 47.
I can see that the file is in my install directory. How do I edit the file? I tried just typing in the code as per the example but it didn't work.

**Comment by igboyes** [comment]
You can edit that file by opening it using the text editor on your system. Finding the file in the file manager and double-clicking it should work.

I wouldn't save learning to edit text files via the command line for later...

**Comment by igboyes** [comment]
You also will need to restart Virtool after changing the config file.

**Comment by jp15nw** [comment]
Great, thank you! It took 3 hours to run but finished. Thank you for all of your help

**Comment by igboyes** [comment]
Please star us at the top of the page if you find Virtool useful. Can I ask which organization you're working at?

**Comment by jp15nw** [comment]
I am a master's student at Brock University working at AAFC - I work with Dr. Griffiths

**Comment by igboyes** [comment]
Good to know. Thanks.

**Comment by CFearer** [comment]
I’ve run into a similar issue (see error code below)

<img width="1365" alt="Screen Shot 2021-11-17 at 2 50 27 PM" src="https://user-images.githubusercontent.com/71893635/142272286-b36d8c96-59a2-4ba0-9345-bdfe426aa6b5.png">

However, I'm not sure where in my config.json file I should make the changes you suggested above? 
<img width="903" alt="Screen Shot 2021-11-17 at 2 51 05 PM" src="https://user-images.githubusercontent.com/71893635/142272370-f532dae7-401d-428c-95b6-d90497ff1195.png">

**Comment by igboyes** [comment]
This may help: https://www.virtool.ca/docs/manual/start/configuration/

You need to figure out the total resources you have available on your host computer and configure `proc` and `mem` accordingly (leaving some headroom). Virtool then carves those numbers up into "small" and "large" job allotments that you can set using `lg_proc` etc.

Here is a configuration for a machine with 32 cores and 64 GB RAM. One large job will use all resources allocated to Virtool.
```json
{
  "data_path": "beech_data",
  "db_connection_string": "mongodb://localhost:27017",
  "db_name": "virtool",
  "watch_path": "beech_samples",
  "proc": 30,
  "mem": 60,
  "lg_proc": 30,
  "lg_mem": 60
}
```
