### ISSUE TITLE
virtool froze at the listening step

### ISSUE THREAD

**Issue by veraspl** [virtool/virtool#1863]
Hi guys, I'm pretty new on GitHub and I registered to search for someone who can help me with my problem with virtool. 

I installed the latest version and all the external software it relies on. When I tried to run the program the following lines showed up:

$ ./run
2020-07-07 17:04:40  app         INFO     Virtool v2.26.2-1-g3659034
2020-07-07 17:04:40  app         INFO     Configuring Sentry
2020-07-07 17:04:40  app         INFO     Listening at http://localhost:9950

And it refused to continue even after an hour. 

Since I don't have a strong coding background, it's totally confusing to me. I've searched for similar issues but didn't encounter any. I'm not sure if this is the suitable platform to ask such a question, so please let me know if it's not.

**Comment by igboyes** [comment]
This means Virtool is ready to go and you need to visit http://localhost:9950 in your browser.

**Comment by veraspl** [comment]
> This means Virtool is ready to go and you need to visit http://localhost:9950 in your browser.

Alas! Forgive my ignorance of the terms. Thank you so much!

**Comment by igboyes** [comment]
You are using a two year old version of Virtool by the way. The current version is 3.9.8.
