### ISSUE TITLE
Add labelling to samples

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#1889]
Allow categorization of samples by label.

- [ ] add `labels` field to samples (multiple labels can be applied to one sample
- [ ] allow setting the `labels` field when the sample is created 
- [ ] allow changing `labels` at sample edit API endpoint
  - if the API request contains `labels` in the JSON body, replace the current sample `labels` with the list from the request
- [ ] return `labels` in `GET` request to:
  - `/api/samples`
  - `/api/samples/:id`
- [ ] find and implement strategy for filtering samples returned by `GET /api/samples` using one or more labels

**Comment by tianshengsui** [comment]
Options of filtering samples endpoint:

- `GET /api/samples?filter=Bug&filter=Info`
- `GET /api/samples?filter=Bug,Info`

I recommend the first format, because Aiohttp can read it as `MultiDictProxy` and then can convert it to a list.
What do you think?

**Comment by igboyes** [comment]
Go with option 1!
