### ISSUE TITLE
Virtool time out/ sleep

### ISSUE THREAD

**Issue by ron-reade** [virtool/virtool#1904]
I have been experiencing a troubling new issue that I have not seen in the past. As I was importing my new data into virtools (400+new sequencing fastq gz files). It was processing the downloads a few at a time, and after a while I noticed it seemed to stop. I clicked on the virtool window, and it went back to the login page. After relogging in, all the files that had not yet been downloaded, or were in process, were lost, and I needed to re-drag and drop them into virtools. Related to this, I have noticed the related phenomenon now that I have moved to creating samples with the imported data. Now, what has happened is as it was creating samples, it appears virtools has timed out again, I have been returned to the login page several times, but my sample creations have not progressed in more than 36hrs. I am not sure what to do from here as they are just spinning and spinning, but not finishing.
Your help is appreciated
![virtool screenshot](https://user-images.githubusercontent.com/58577154/95116191-82720300-06fb-11eb-859d-3fadb48a2256.png)

**Comment by igboyes** [comment]
> t was processing the downloads a few at a time, and after a while I noticed it seemed to stop. I clicked on the virtool window, and it went back to the login page.

Your session is expiring. Please click on **Remember Me** next time you log in. Logout and login again to force this. The default session length for Virtool is 30 minutes. Clicking **Remember Me** extends this to 30 days.

1. Please check your **Jobs** view for errors and post here.
2. Please restart Virtool so it has a chance to clean up corrupted data.

**Comment by ron-reade** [comment]
I have always had Remember me selected, and it still seems to time out, but my credentials are already filled in, so all I have to do is hit enter when that page pops up. Can I restart virtools without losing the current 19 jobs? See screenshot of my jobs view.
![Jobs screenshot](https://user-images.githubusercontent.com/58577154/95144340-4192e200-072d-11eb-9279-6a0b38e89284.png)

**Comment by igboyes** [comment]
No you can't restart Virtool without losing those jobs.

I can tell from the color of the progress bars that you are not using the latest version of Virtool. Please update.

**Comment by igboyes** [comment]
Please re-open if problem persists.
