### ISSUE TITLE
Pathoscope view unable to sort

### ISSUE THREAD

**Issue by ron-reade** [virtool/virtool#1906]
The sort button on the Pathoscope view does not work, so you can no longer sort by Depth, or Weight, and can only sort by the default coverage, as selecting any of these options does not resort the data.

**Comment by ron-reade** [comment]
I was already using 4.0.1, but just tried updating to 4.0.2 from Github, but virtools will not restart now (using the Service script), I will try to trouble shoot and see what I can figure out.
Ron

**Comment by ron-reade** [comment]
Just tried sorting with Depth using 4.0.2... still does not re-sort?
![4-0-2 installed](https://user-images.githubusercontent.com/58577154/95248264-e5cb6600-07cb-11eb-9a48-969487279481.png)
![DataSort](https://user-images.githubusercontent.com/58577154/95248531-45297600-07cc-11eb-856b-f0ceb0fc2d7a.png)

**Comment by igboyes** [comment]
What browser are you using?

**Comment by ron-reade** [comment]
I am using FireFox on Kubuntu 
![Browser](https://user-images.githubusercontent.com/58577154/95267245-a449b380-07e9-11eb-8360-2b47941d773d.png)
![Kubuntu](https://user-images.githubusercontent.com/58577154/95267256-aa3f9480-07e9-11eb-846b-a01f1ffcd8dc.png)

**Comment by igboyes** [comment]
Your operating system is past end-of-life. [Here is an article about it](https://itsfoss.com/ubuntu-19-04-end-of-life/). You are no longer receiving updates to Firefox as a result.

Please do the following in Firefox:
1. Navigate to Virtool
2. Type Ctrl+Shift+C
3. Verify that the developer tools will appear
4. Go to the **Debugger Tab**
5. Click through Main Thread > _ip\_address_ > static

It should look something like this:

![image](https://user-images.githubusercontent.com/5943558/95272552-74081200-07f5-11eb-93a1-02baba3b2dd7.png)

Report back the name of the first file in static. It should be something like `1.app.f6ccc45b.js`.

**Comment by ron-reade** [comment]
Hi Ian,
This is what I get...
![FireFox details](https://user-images.githubusercontent.com/58577154/95359415-f7ba1100-087e-11eb-9aa5-01da6e5b2f77.png)

**Comment by ron-reade** [comment]
Getting the latest Kubuntu installed is going to take some work, but I did manage to force my computer to install the new FireFox installed. after restarting and getting virtool up and running again... I still can not sort my data by anything else but coverage. I have attached a screenshot
![FirefoxNew](https://user-images.githubusercontent.com/58577154/95404335-99665000-08c9-11eb-8fd8-56966e69090d.png)

**Comment by igboyes** [comment]
I can't reproduce this bug in the same browser and Virtool version.

Please use Ctrl+Shift+C to open the developer tools and check if there are errors in the **Console** tab.

**Comment by ron-reade** [comment]
Hey, sorry...super busy day... this is what my console tab looks like... The second pane is the expanded warning tab... all 35 are the same.

![Console tab#1](https://user-images.githubusercontent.com/58577154/95637205-04d52c80-0a46-11eb-8eaf-7d3bd98bda60.png)
![Console tab#2](https://user-images.githubusercontent.com/58577154/95637210-07378680-0a46-11eb-985b-c0292286f487.png)

**Comment by ron-reade** [comment]
I just discovered something that might help... It appears that none of the drop down menus work for me... can't use the Export button, and can't log out of my profile under the account drop down menu either.

**Comment by igboyes** [comment]
Managed to replicate. Dropdowns intermittently fail to open on click.
