### ISSUE TITLE
Sample Creation Fail

### ISSUE THREAD

**Issue by ron-reade** [virtool/virtool#1908]
I just experienced another issue with sample creation, I was rebuilding the jobs I lost from the last issue where virtool would not complete the sample creation,and this time, I noticed that 6 of them just disappeared from my sample list view. When I went into the jobs tab, I could see that they all failed in the same way... see attachement...
![Sample creating errors](https://user-images.githubusercontent.com/58577154/95360306-0d7c0600-0880-11eb-8f8b-b28071f7d2e7.png)

**Comment by igboyes** [comment]
Will be resolved in 4.1.0 when released.
