### ISSUE TITLE
Substraction is removed after changing the view.

### ISSUE THREAD

**Issue by DriesSchaumont** [virtool/virtool#1939]
Hello! 

I am encountering an issue where freshly added substractions disappear from the list once the view is changed. 
Creating a new substraction works fine (the job is marked as complete and the substraction is shown in the list), 
but once I change the view to another page, or tab (e.g 'files') the substraction disappears. 
I can however view the substraction from the job page and by clicking on the id, but I cannot use it when importing samples.
When virtool is restarted, the substraction reappears and I can use it in samples and the list seems to be stable.

I am using virtool v4.1.0. 
Might be related: #812

**Comment by igboyes** [comment]
This has been resolved (#1925) and the fix will be included in release 4.1.1. Sorry for the inconvenience.

**Comment by igboyes** [comment]
@DriesSchaumont Is this issue resolved for you in 4.1.1? Please star the repo to support Virtool development!

**Comment by DriesSchaumont** [comment]
Yes, everything seems to behaving as expected. Thank you for the quick response!
