### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory While Starting Server or Runner

### ISSUE THREAD

**Issue by ColeVoelpel** [virtool/virtool#1942]
When starting up the server or runner using the command:
```
python run.py server --redis-connection-string 127.0.0.1:6379
``` 

The error was bypassed by adding `redis://` before the IP.

The stack trace for the error is:
![Screenshot from 2020-10-22 10-15-09.png](https://images.zenhubusercontent.com/5f7632a46450e00e7ee979d0/757b69cc-ba41-49d6-9845-ba3cb1258c8c)

**Comment by igboyes** [comment]
@tianshengsui Please add check for `redis://` prefix being present in provided Redis connection string. Log fatal and exit with code 1 if check fails.
