### ISSUE TITLE
Changing 'read_index' implementation in Pathoscope script

### ISSUE THREAD

**Issue by Mallory-Loria** [virtool/virtool#1959]
-consider changing 
```
u[read_index][1][0] = math.exp(u[read_index][1][0] * scaling_factor)
```

to a matrix where certain vector is multiplied by scaling factor instead of a dictionary

-also change min_score to float type

**Comment by igboyes** [comment]
Sounds good! Check here for markdown tips to get your bullets to format properly:
https://guides.github.com/features/mastering-markdown/
