### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#1966]
Use GitHub actions instead of DroneCI.

- [ ] push built package to GitHub release when tag is created
  - currently a build is triggered on release; there is a period of time when a release is public and there is no `virtool.tar.gz` file available
  - check if it is possible to build when a draft release is saved
- [ ] save artifacts (unpublished builds) using GitHub artifacts; this will replace Digitalocean Spaces
- [ ] push coverage to Codacy (`CODACY_PROJECT_TOKEN` has been added as secret already)
- [ ] remove .drone.yml

**Comment by tianshengsui** [comment]
> check if it is possible to build when a draft release is saved

It seems that GitHub Actions can not be triggered for draft releases currently. [See here](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#release)
