### ISSUE TITLE
Make host/background read subtraction optional

### ISSUE THREAD

**Issue by peterk87** [virtool/virtool#1972]
It'd be nice if host subtraction was optional and not performed by default on certain samples. 

We typically perform background sequence subtraction using Kraken2/Centrifuge taxonomic classification results using big indexes where we typically remove anything non-viral, but keep unclassified reads just in case they may contain novel virus sequence.

Also for a lot of amplicon sequencing, we don't expect much background sequence and are just interested in read mapping, variant calling and consensus sequence generation.

**Comment by igboyes** [comment]
Converted to [Clubhouse epic](https://app.clubhouse.io/virtool/epic/51).
