### ISSUE TITLE
Placeholder samples

### ISSUE THREAD

**Issue by peterk87** [virtool/virtool#1973]
It would be nice to be able to create placeholder samples with no sequences that are present in anticipation of sequence data being generated and uploaded to Virtool shortly.

**Comment by igboyes** [comment]
I have been considering the utility of allowing multiple "sub-samples" for a single sample as it exists in Virtool now. I think this would integrate well with your idea.

**Comment by peterk87** [comment]
Would an example of a "sub-sample" be a viral genome assembled and associated reads from a sample's metagenomic reads? The term "sub-sample" might be a bit confusing (e.g. read subsampling), what about "derived sample"? Is that kind of what you mean? It would definitely be very useful to define and keep track of lineage of a particular genome if it used for downstream analyses.

**Comment by igboyes** [comment]
Closing. Re-open if not covered in #1987.
