### ISSUE TITLE
More information in logging

### ISSUE THREAD

**Issue by peterk87** [virtool/virtool#1974]
It'd be nice to have more information in the logs, e.g. function name, line number, full module name, so it'd be easier to debug issues when developing.

[virtool/logs.py](https://github.com/virtool/virtool/blob/master/virtool/logs.py) logging with more info:

```python
import logging.handlers

import coloredlogs


def configure(verbose=False):
    logging_level = logging.DEBUG if verbose else logging.INFO

    logging.captureWarnings(True)

    log_format = '{asctime:<20} {module:<11} {levelname:<8} {message} [{name}:{funcName}:{lineno}]'

    coloredlogs.install(
        level=logging_level,
        fmt=log_format,
        style='{'
    )

    logger = logging.getLogger()

    handler = logging.handlers.RotatingFileHandler("virtool.log", maxBytes=1000000, backupCount=5)
    handler.setFormatter(logging.Formatter(log_format, style='{'))

    logger.addHandler(handler)

    return logger
```

**Comment by igboyes** [comment]
For this issue specifically, we can change the formatter based on the `dev` configuration value to provide debug information. Without `dev` set, logging should be quite sparse like any other application.

I would like to create a logging epic to generally improve logging and determine how to integrate logging from multiple Virtool instances with a logging platform (eg. Azure monitoring, [ELK](https://www.elastic.co/log-monitoring)).

**Comment by peterk87** [comment]
Sounds good! It'd be nice to have different streams/files for logging (access, events, error, analyses, etc).

What are your thoughts on structured logging (e.g. [structlog](https://github.com/hynek/structlog))? I've never used it before, but I can see the potential benefits.

**Comment by peterk87** [comment]
@igboyes What do you think about adding [Rich](https://github.com/willmcgugan/rich) for logging? It has a ton of features, most of which we'd probably never use (unless you want to emojify logs :fire:). Tracebacks like [this](https://github.com/willmcgugan/rich#tracebacks) for dev would be really nice or being able to pretty print local vars. However, I'm not sure if the current library coloredlogs has similar features.

**Comment by igboyes** [comment]
Yup. I have created a story for this (ch-114).

@jakeale has already used Rich for `virtool-cli` so I am putting him on it. I think we can point him to any further logging-related stories you may want to create.

Closing this issue.
