### ISSUE TITLE
Less UI modals

### ISSUE THREAD

**Issue by peterk87** [virtool/virtool#1975]
There's a lot of modals in Virtool used for editing entity info, triggering analyses, etc. However, if a user accidentally clicks outside of a modal, the modal state is lost and the user needs to get back to that state manually. It'd be nice if these modals were transitioned to dedicated pages for creating/editing info, setting up analyses, etc especially when multiple pieces of info are required. If possible, intermediate state should be saved in case of issues like some sequences weren't uploaded yet or a particular DB hasn't been set up yet.

**Comment by igboyes** [comment]
I absolutely agree on this and have wanted to do it for sometime.

**Comment by igboyes** [comment]
Closing this. We are going in the general direction of moving modals to dedicated views where it makes sense.
