### ISSUE TITLE
Some UI elements too wide

### ISSUE THREAD

**Issue by peterk87** [virtool/virtool#1976]
Some of the UI elements, particularly input text boxes are awkwardly wide taking up over 90% of the total screen width on a typical widescreen monitor when the browser window is maximized.

For example, the sample search box is really wide and the sample create button is kind of hidden away to the right

![image](https://user-images.githubusercontent.com/4203424/99694996-a6db3200-2a52-11eb-92f1-7a73f1da5f53.png)

**Comment by igboyes** [comment]
Let's all find some examples of how this could be accomplished and be aesthetically pleasing and provide good UX.

I think a left-justified layout would work well. Views and components that work well with a width limit would look good and not have ridiculous dimensions like your example screenshot. Data-intensive analysis viewers could stretch to the full available width.

Here is an example of what I mean:
![image](https://user-images.githubusercontent.com/5943558/100166365-6ecc5880-2e71-11eb-83f8-2a1f72339029.png)

**Comment by igboyes** [comment]
Moved to [Clubhouse epic](https://app.clubhouse.io/virtool/epic/62).
