### ISSUE TITLE
Analyses page

### ISSUE THREAD

**Issue by peterk87** [virtool/virtool#1978]
As more workflows and analyses are added to Virtool, I can see a dedicated Analyses page being necessary which would primarily consist of a table with various attributes about each particular analysis.

- analysis ID
- workflow name/ID
- time started, finished
- analysis status including progress, error messages
- project name/ID
- sample(s) analysed
- analysis params

**Comment by igboyes** [comment]
Moved to Clubhouse story: ch-113.
