### ISSUE TITLE
Bulk sample creation/editing

### ISSUE THREAD

**Issue by peterk87** [virtool/virtool#1980]
It would be nice to copy-paste a table of sample information into Virtool (and maybe even allow upload of a TSV/CSV/Excel file with sample info) to create multiple samples in Virtool at once. It would also be nice to edit multiple samples at the same time in a table like in Excel with cell value drag-down. 

- Possibly related to #1973 since requiring that reads be uploaded first is not conducive to bulk sample creation

**Comment by igboyes** [comment]
I believe this is now covered in:
#1986 
#1985

These are part of Zenhub epic #1982.
