### ISSUE TITLE
Research alternative charting library

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#1989]
Find a charting library that provides a simpler API than D3.

- should be small
- should be a modern, active JS project
- D3 will still have to be used so it is an advantage if the library is based on D3
- should work well with React

**Comment by peterk87** [comment]
Below are some options for higher level charting and data viz libraries that are actively developed. I've only used Plotly and Vega-Lite:

---

[Plotly.js](https://plotly.com/javascript/) 

> Built on top of d3.js and stack.gl, Plotly.js is a high-level, declarative charting library. plotly.js ships with over 40 chart types, including 3D charts, statistical graphs, and SVG maps. plotly.js is free and open source and you can view the source, report issues or contribute on GitHub. 

- declarative
- uses D3
- offers a lot of interactivity by default (zooming, panning, selection, saving to PNG/SVG/etc)
- [plotly Python library](https://plotly.com/python/); server side rendering?
- nice Jupyter Notebook integration for easy prototyping of new visualizations

---

> [Vega-Lite](https://vega.github.io/vega-lite/) is a high-level grammar of interactive graphics. It provides a concise, declarative JSON syntax to create an expressive range of visualizations for data analysis and presentation. 

- declarative
- easy to reason about
- easy to configure

---

> [ECharts](https://echarts.apache.org/en/index.html): A declarative framework for rapid construction of web-based visualization

- [paper in Visual Informatics](https://www.sciencedirect.com/science/article/pii/S2468502X18300068)
- follows [The Grammar of Graphics](https://link.springer.com/chapter/10.1007/978-3-642-21551-3_13)
- very impressive examples (e.g. [draw NYC streets in 1 million lines](https://echarts.apache.org/next/examples/en/editor.html?c=lines-ny))
- lots of examples
- performant

---

[Victory](https://formidable.com/open-source/victory/)

> React.js components for modular charting and data visualization.

- made for React
- not very many examples, but the examples they do have are slick

---

> - should be small

I'm not too sure how to best gauge this. Are we talking gzipped minified tree shaken diff in size?

--- 

Thoughts/opinions:

- It'd be great to be able to specify new visualizations and charts declaratively when possible with the option to fallback to D3.js when greater control is needed over how specific visual elements look. 
- I'm a huge fan of [ggplot2](https://ggplot2.tidyverse.org/) and it's use of the Grammar of Graphics. Having that kind of high level control over data viz in a JS library would be great.
- The high-level data viz library should have easy configuration to add tooltips, legends, panning, zooming, selection, ability to set custom event handlers.
- Good performance would be nice especially for large/complex data visualizations. There's definitely a limit to how many SVG elements you should have in a single viz. Canvas seems to be a lot more forgiving. WebGL is a nice option for very large viz (millions of data points; large graphs; anything 3D).
