### ISSUE TITLE
Allow zero or more subtractions when creating analyses

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#1991]
Currently, we accept a single `subtraction_id` when creating an analysis at `POST /api/samples/:id/analyses`.

- accept an array of subtraction IDs called `subtractions`
- extend subtraction check for existence of all subtraction IDs in the array
- store an array of subtraction IDs in the database
- check all other usages of subtraction that may need to be updated

**Comment by tianshengsui** [comment]
@igboyes Do you want to store an empty list when no subtraction is provided?

**Comment by igboyes** [comment]
Yes
