### ISSUE TITLE
Stalled jobs on branch release-5.0.0

### ISSUE THREAD

**Issue by peterk87** [virtool/virtool#2033]
- branch: release-5.0.0
- commit: a8691890a05c5cf95d6e1c19db63d7aede7d5829

# Setup

I'm running Redis, Mongo and Postgres using Docker-Compose with `docker-compose.dev.yml` and running Virtool server with the following command:

```bash
$ ./run.py --dev server
```

My `config.json`

```json
{
    "db_name": "virtool",
    "db_connection_string": "mongodb://localhost:27017",
    "redis_connection_string": "redis://localhost:6379",
    "postgres_connection_string": "postgresql+asyncpg://virtool:virtool@localhost/virtool"
}
```

I am running the `run.py` script with an activated Conda env with the Python and external dependencies installed that are required by Virtool.

# Issue

When I try to create a small subtraction (i.e. bowtie2 index), the only log messages I see are:

```
2021-01-14 13:35:33  dispatcher  DEBUG    Dispatched subtraction.insert [root:dispatch:183]
2021-01-14 13:35:33  connection  DEBUG    Creating tcp connection to ('localhost', 6379) [aioredis:create_connection:110]
2021-01-14 13:35:33  dispatcher  DEBUG    Dispatched jobs.insert [root:dispatch:183]
2021-01-14 13:35:33  interface   DEBUG    Enqueued job: npayn8r9 [virtool.jobs.interface:enqueue:21]
```
These are the only log messages I see about this job.

Inside the Redis Docker container:

```bash
$ redis-cli

127.0.0.1:6379> keys *
1) "jobs_sm"
127.0.0.1:6379> lrange jobs_sm 0 2
1) "ejvn4xw6"
2) "npayn8r9"
```

The job `npayn8r9` is being stored in the `jobs_sm` list in Redis, but nothing seems to happen after that. The subtraction FASTA is only 5MB (Salmonella [AL513382.1](https://www.ncbi.nlm.nih.gov/nuccore/AL513382.1/)) so `bowtie2-build` should be very quick (~1 second).

Other jobs are also not being executed and I'm not sure why. 

I think @ColeVoelpel mentioned that he had similar issues with this branch. 

Jobs work fine for me on master branch (version 4) with the above setup.

**Comment by igboyes** [comment]
You need to have an runner instance as well. See README:

https://github.com/virtool/virtool/tree/release-5.0.0#runner

**Comment by peterk87** [comment]
Thanks @igboyes! I'll be sure to check the docs more closely next time.
