### ISSUE TITLE
V1.8.5 "NuVs" analysis error

### ISSUE THREAD

**Issue by maplexuci** [virtool/virtool#232]
Error message:

Python Error

Traceback (most recent call last):
File "virtool/job.py", line 116, in run stage_method()
File "virtool/analysis.py", line 873, in vfam annotation_id = self.db.hmm.find_one({"cluster": int(cluster_id)}, {"_id": True})["_id"]
TypeError: 'NoneType' object is not subscriptable

profiles.hmm file is in the <data_path>/hmm directory.

**Comment by igboyes** [comment]
This is caused by the HMM annotations not being in the database.

I am going to put these annotations in a new repository along with the profiles I provided to you earlier.

I'll post back here when its ready.

**Comment by maplexuci** [comment]
Good to know. Thanks.

**Comment by igboyes** [comment]
The new repo is [virtool/virtool-hmm](https://github.com/virtool/virtool-hmm).

There is an import button in the HMM viewer in Virtool v1.8.5 that you can to make use of the ``annotations.json.gz`` file.

I've just realized that the import function has not been reproduced in v2.0.0, so I will have to do this in the next little while. You will not be able to use NuVs in v2.0.0 for the time being

**Comment by maplexuci** [comment]
Click "HMM" label under "Viruses" in virtool 1.8.5 results no response, and stops response to any click to anywhere until refresh the browser. So could not go further to import the annotation file.
Take your time and I will be back to the lab next Monday continuing playing with it.
Have a great weekend!

**Comment by igboyes** [comment]
Resolved for v2.0.0.
