### ISSUE TITLE
Allow importation of HMM annotations

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#234]
Raised from #232 

- need to replicate this from v1.8.5 before releasing v2.0.0
- consider direct download from Github

**Comment by igboyes** [comment]
Implemented with direct download from GitHub.

Resolved in #241

**Comment by maplexuci** [comment]
Where to put this annotations.json.gz file?

**Comment by igboyes** [comment]
Using that file will be supported in beta.3. This should be done today or tomorrow.

To see how it will work, read [here](https://docs.virtool.ca/hmms.html#official_models).

**Comment by igboyes** [comment]
You should be able to download beta.3 soon. It is just being tested and packaged.

You will have to delete any previous profiles.hmm file in ``<data_path>/hmm`` in order for the auto-installation to work.

Let me know of any problems in a new issue.

**Comment by maplexuci** [comment]
Sound great! I will try it tomorrow.

**Comment by maplexuci** [comment]
It keeps like this when click the HMM on the navigation bar. No error message shows up in terminal, Nothing else is affected.
![screenshot from 2017-11-20 10 39 28](https://user-images.githubusercontent.com/8636318/33026908-9f7e1c84-cddf-11e7-81e2-7fda51b44b74.png)

**Comment by igboyes** [comment]
Have you removed the old profiles.hmm file from ``<data_path>/hmm``?

**Comment by maplexuci** [comment]
yes, I did.

**Comment by igboyes** [comment]
I have figured out what is causing this an it will be fixed in **beta.5**.

Please open a new issue for any more problems with the HMM functions.
