### ISSUE TITLE
web_protocol ERROR: Error handling request

### ISSUE THREAD

**Issue by maplexuci** [virtool/virtool#237]
A job shows "waiting" forever, when clicking the red cross to delete it, the following message shows up in the terminal and then anything in virtool becomes unviewable (blank white page when click) and unable to logout:

2017-11-07 16:53:56  web_protocol ERROR    Error handling request
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 422, in start
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/web.py", line 306, in _handle
  File "/home/travis/build/virtool/virtool/virtool/error_pages.py", line 14, in middleware_handler
  File "/home/travis/build/virtool/virtool/virtool/app_auth.py", line 96, in middleware_handler
  File "/home/travis/build/virtool/virtool/virtool/handlers/jobs.py", line 95, in cancel
  File "/home/travis/build/virtool/virtool/virtool/job_manager.py", line 116, in cancel
KeyError: 'ycwovqus'

**Comment by igboyes** [comment]
Can you post a screenshot of your _Settings_ > _Jobs_ view?

**Comment by maplexuci** [comment]
![screenshot from 2017-11-08 13 28 42](https://user-images.githubusercontent.com/8636318/32567300-d8050a96-c488-11e7-8a20-fe4f623584da.png)

**Comment by maplexuci** [comment]
![screenshot from 2017-11-08 13 28 42](https://user-images.githubusercontent.com/8636318/32567323-e65a8e72-c488-11e7-9ee7-70665fc0bd9d.png)

**Comment by maplexuci** [comment]
![screenshot from 2017-11-08 13 28 42](https://user-images.githubusercontent.com/8636318/32567323-e65a8e72-c488-11e7-9ee7-70665fc0bd9d.png)

**Comment by maplexuci** [comment]
![screenshot from 2017-11-08 13 28 42](https://user-images.githubusercontent.com/8636318/32567323-e65a8e72-c488-11e7-9ee7-70665fc0bd9d.png)

**Comment by maplexuci** [comment]
![screenshot from 2017-11-08 13 28 42](https://user-images.githubusercontent.com/8636318/32567323-e65a8e72-c488-11e7-9ee7-70665fc0bd9d.png)

**Comment by maplexuci** [comment]
![screenshot from 2017-11-08 13 28 42](https://user-images.githubusercontent.com/8636318/32567323-e65a8e72-c488-11e7-9ee7-70665fc0bd9d.png)

**Comment by igboyes** [comment]
Are you able to start another job if you restart the server and refresh the browser?

**Comment by maplexuci** [comment]
Yes, I can start other jobs.

**Comment by maplexuci** [comment]
![screenshot from 2017-11-08 17 24 10](https://user-images.githubusercontent.com/8636318/32578026-b4dbd150-c4a9-11e7-90fb-3eb2a35325bb.png)

**Comment by igboyes** [comment]
I'm not sure why that happened. It is not a real job anymore, just a 'ghost' of it in the database.

I will make sure that this ghost job can be removed or cleaned up.
