### ISSUE TITLE
Support for Spring file compression

### ISSUE THREAD

**Issue by KingBain** [virtool/virtool#2388]
Lets add Spring compression to the tool 

https://github.com/shubhamchandak94/Spring

**This issue is going to be kind of gross, but I'm going to paste the slack chat into the ticket below this post.** 

_in the lunch meeting today, we got into talking about the fastq files .... why they get so huge
I found that topic kind of interested. dived into a bit

playing with the compression options and unpacking the gunzip'd files

strangely eanough, ended up learning about all these whitepapers that speak about girthy fastq files

One of the tools they had to compress the files was Spring

the other being LFastqC

i haven't round tripped a compression and decompressing using spring, but it seems to do an ok job

file sizes for comparison
![image](https://user-images.githubusercontent.com/367922/133800037-fc066037-1c65-45a3-bac6-7428dacbd7e7.png)

from 3.5gigs to 500 megs is like 80-85% compression

vs 3.5 gigs to 1 gig is like 65% compression

screwed up my screenshot, but hopefully its readable
![image](https://user-images.githubusercontent.com/367922/133800128-364ce34f-f2eb-415f-a372-3eb94f48c45f.png)

round tripping was successful. compress then decompress and diff; confirmed the same file .

![image](https://user-images.githubusercontent.com/367922/133800179-bfa7a77d-1a24-4d7b-ba4f-a608c2a2ad9c.png)_

**Comment by KingBain** [comment]
Looks like utils.py contains the compression and decompression commands 
![image](https://user-images.githubusercontent.com/367922/133800479-7685df8e-21a8-42a6-a77b-0300c35944d8.png)

**Comment by KingBain** [comment]
I think my approach will be to replicate what pigz is doing but for spring. Unsure about how to write the tests for this though :/ 


also Pigz isn't listed in the Required software

**Comment by igboyes** [comment]
I am closing this.

Compression or down-tiering storage will be a feature that users can opt to use. I see this being abstracted behind an **Archive Sample** functionality that can be used to minimize storage costs for that samples as much as possible.

Any compression or change in storage medium will mean slower workflows and slower download of data.

We will do some research (at some point) into the following:
* Well-maintained and efficient compression for FASTQ and other formats. I'm not sure Spring fits the bill.
* Allowing changes in storage tiers. This needs to be agnostic of backing storage.

This feature is being tracked internally.
