### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by maplexuci** [virtool/virtool#242]
Does the beta versions get updated automatically? I've noticed that current release is beta.2. But no upgrade information is available.
![screenshot from 2017-11-13 11 01 01](https://user-images.githubusercontent.com/8636318/32735204-21a4ec84-c862-11e7-90b0-f256439aa722.png)
![screenshot from 2017-11-13 11 01 07](https://user-images.githubusercontent.com/8636318/32735205-21b66306-c862-11e7-9233-f6435816b2b3.png)

**Comment by igboyes** [comment]
That feature is not working in beta.1 (bug).

If you manually replace the Virtool program files with those from the beta.2 release, the updates will work. The feature needs a bit more polish, but it is functional.
