### ISSUE TITLE
Installation of References and HMMs failing

### ISSUE THREAD

**Issue by Dave587** [virtool/virtool#2433]
As per the issue mentioned by msEN12 after clicking the Install button nothing happens.

Related messages from the virtool.log file: (redacted server and domain names)
When trying to install References
Oct 27 11:14:44 <server_name> run[3973]: 2021-10-27 11:14:44  web_log     INFO     172.20.94.23 [27/Oct/2021:15:14:44 +0000] "POST /api/refs HTTP/1.1" 502 764 "https://<domain_name>/refs" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0"

When trying to install HMMs.. the page changes to display Installing and Download, but nothing actually happens
Oct 27 11:15:43 <server_name> run[3973]: 2021-10-27 11:15:43  web_log     INFO     172.20.94.23 [27/Oct/2021:15:15:43 +0000] "POST /api/hmms/status/updates HTTP/1.1" 400 771 "https://<domain_name>/hmm" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0"

Also took a packet capture during the Reference installation attempt.. using WireShark we can see a successful conversation taking place ie.. Ack, Syn-Ack, Fin-Ack, Ack. So looks like the server is reaching out and contacting the destination but either not finding what it asked for or cant do what it needs to after retrieving the content.

I was able to manually download the References and get those installed, but I cant see a way to do that with the HMMs

**Comment by igboyes** [comment]
I am going to improve logging for this next week. Big workload at the moment, so bear with me.

**Comment by Dave587** [comment]
Thanks for the feedback, much appreciated

**Comment by Dave587** [comment]
I had meant to include the output of the Developer Tools Console from a browser session in case that might assist.
``
`1.app.2e929560.js:2 POST https://<Domain_Name>/api/refs 502 (Bad Gateway)
(anonymous) @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
y._end @ 1.app.2e929560.js:2
y.end @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
i.then @ 1.app.2e929560.js:2
T @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
v @ 1.app.2e929560.js:2
h @ 1.app.2e929560.js:2
H @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
v @ 1.app.2e929560.js:2
h @ 1.app.2e929560.js:2
H @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
v @ 1.app.2e929560.js:2
P.<computed> @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
v @ 1.app.2e929560.js:2
h @ 1.app.2e929560.js:2
c @ 1.app.2e929560.js:2
s @ 1.app.2e929560.js:2
put @ 1.app.2e929560.js:2
t @ 1.app.2e929560.js:2
S.e.put @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
d @ 1.app.2e929560.js:2
g @ 1.app.2e929560.js:2
h @ 1.app.2e929560.js:2
S.c.put @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
onRemote @ 7.app.2e929560.js:1
u @ 1.app.2e929560.js:2
d @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
b @ 1.app.2e929560.js:2
ut @ 1.app.2e929560.js:2
it @ 1.app.2e929560.js:2
ct @ 1.app.2e929560.js:2
ht @ 1.app.2e929560.js:2
N @ 1.app.2e929560.js:2
z @ 1.app.2e929560.js:2
Zt @ 1.app.2e929560.js:2
Jt @ 1.app.2e929560.js:2
t.unstable_runWithPriority @ 1.app.2e929560.js:2
Vo @ 1.app.2e929560.js:2
R @ 1.app.2e929560.js:2
Gt @ 1.app.2e929560.js:2
i @ 1.app.2e929560.js:2
Show 20 more frames
1.app.2e929560.js:2 TypeError: Cannot read properties of undefined (reading 'captureException')
    at O (app.2e929560.js:2)
    at wt (app.2e929560.js:2)
    at 1.app.2e929560.js:2
    at b (1.app.2e929560.js:2)
    at 1.app.2e929560.js:2
    at 1.app.2e929560.js:2
    at dispatch (1.app.2e929560.js:2)
    at 1.app.2e929560.js:2
    at 1.app.2e929560.js:2
    at d (1.app.2e929560.js:2)
    at g (1.app.2e929560.js:2)
    at h (1.app.2e929560.js:2)
    at P.<computed> (1.app.2e929560.js:2)
    at 1.app.2e929560.js:2
    at v (1.app.2e929560.js:2)
    at h (1.app.2e929560.js:2)
    at H (1.app.2e929560.js:2)
    at 1.app.2e929560.js:2
    at v (1.app.2e929560.js:2)
    at h (1.app.2e929560.js:2)
    at c (1.app.2e929560.js:2)
    at 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
g @ 1.app.2e929560.js:2
g @ 1.app.2e929560.js:2
a @ 1.app.2e929560.js:2
t.cont @ 1.app.2e929560.js:2
h @ 1.app.2e929560.js:2
c @ 1.app.2e929560.js:2
n @ 1.app.2e929560.js:2
c @ 1.app.2e929560.js:2
g @ 1.app.2e929560.js:2
a @ 1.app.2e929560.js:2
t.cont @ 1.app.2e929560.js:2
g @ 1.app.2e929560.js:2
a @ 1.app.2e929560.js:2
t.cont @ 1.app.2e929560.js:2
g @ 1.app.2e929560.js:2
a @ 1.app.2e929560.js:2
t.cont @ 1.app.2e929560.js:2
h @ 1.app.2e929560.js:2
c @ 1.app.2e929560.js:2
g @ 1.app.2e929560.js:2
a @ 1.app.2e929560.js:2
t.cont @ 1.app.2e929560.js:2
h @ 1.app.2e929560.js:2
c @ 1.app.2e929560.js:2
g @ 1.app.2e929560.js:2
a @ 1.app.2e929560.js:2
t.cont @ 1.app.2e929560.js:2
h @ 1.app.2e929560.js:2
c @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
d @ 1.app.2e929560.js:2
g @ 1.app.2e929560.js:2
h @ 1.app.2e929560.js:2
P.<computed> @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
v @ 1.app.2e929560.js:2
h @ 1.app.2e929560.js:2
H @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
v @ 1.app.2e929560.js:2
h @ 1.app.2e929560.js:2
c @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
Promise.then (async)
i.then @ 1.app.2e929560.js:2
T @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
v @ 1.app.2e929560.js:2
h @ 1.app.2e929560.js:2
H @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
v @ 1.app.2e929560.js:2
h @ 1.app.2e929560.js:2
H @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
v @ 1.app.2e929560.js:2
P.<computed> @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
v @ 1.app.2e929560.js:2
h @ 1.app.2e929560.js:2
c @ 1.app.2e929560.js:2
s @ 1.app.2e929560.js:2
put @ 1.app.2e929560.js:2
t @ 1.app.2e929560.js:2
S.e.put @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
d @ 1.app.2e929560.js:2
g @ 1.app.2e929560.js:2
h @ 1.app.2e929560.js:2
S.c.put @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
onRemote @ 7.app.2e929560.js:1
u @ 1.app.2e929560.js:2
d @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
b @ 1.app.2e929560.js:2
ut @ 1.app.2e929560.js:2
it @ 1.app.2e929560.js:2
ct @ 1.app.2e929560.js:2
ht @ 1.app.2e929560.js:2
N @ 1.app.2e929560.js:2
z @ 1.app.2e929560.js:2
Zt @ 1.app.2e929560.js:2
Jt @ 1.app.2e929560.js:2
t.unstable_runWithPriority @ 1.app.2e929560.js:2
Vo @ 1.app.2e929560.js:2
R @ 1.app.2e929560.js:2
Gt @ 1.app.2e929560.js:2
i @ 1.app.2e929560.js:2
Show 59 more frames
1.app.2e929560.js:2 The above error occurred in task Cc
    created by Cc
    created by Cc
    created by throttle(REMOTE_REFERENCE_REQUESTED, Cc)
    created by Wa
    created by Wa
Tasks cancelled due to error:
throttle(REMOTE_REFERENCE_REQUESTED, Cc)
throttle(CREATE_REFERENCE_REQUESTED, xc)
throttle(IMPORT_REFERENCE_REQUESTED, Tc)
throttle(CLONE_REFERENCE_REQUESTED, Rc)
takeEvery(EDIT_REFERENCE_REQUESTED, vc)
takeLatest(GET_REFERENCE_REQUESTED, Ic)
takeLatest(FIND_REFERENCES_REQUESTED, wc)
throttle(REMOVE_REFERENCE_REQUESTED, _c)
takeEvery(ADD_REFERENCE_USER_REQUESTED, Uc)
takeEvery(EDIT_REFERENCE_USER_REQUESTED, Pc)
takeEvery(REMOVE_REFERENCE_USER_REQUESTED, kc)
takeEvery(ADD_REFERENCE_GROUP_REQUESTED, Nc)
takeEvery(EDIT_REFERENCE_GROUP_REQUESTED, Lc)
takeEvery(REMOVE_REFERENCE_GROUP_REQUESTED, Qc)
takeEvery(CHECK_REMOTE_UPDATES_REQUESTED, Ac)
takeEvery(UPDATE_REMOTE_REFERENCE_REQUESTED, Fc)
(anonymous) @ 1.app.2e929560.js:2
g @ 1.app.2e929560.js:2
g @ 1.app.2e929560.js:2
a @ 1.app.2e929560.js:2
t.cont @ 1.app.2e929560.js:2
h @ 1.app.2e929560.js:2
c @ 1.app.2e929560.js:2
n @ 1.app.2e929560.js:2
c @ 1.app.2e929560.js:2
g @ 1.app.2e929560.js:2
a @ 1.app.2e929560.js:2
t.cont @ 1.app.2e929560.js:2
g @ 1.app.2e929560.js:2
a @ 1.app.2e929560.js:2
t.cont @ 1.app.2e929560.js:2
g @ 1.app.2e929560.js:2
a @ 1.app.2e929560.js:2
t.cont @ 1.app.2e929560.js:2
h @ 1.app.2e929560.js:2
c @ 1.app.2e929560.js:2
g @ 1.app.2e929560.js:2
a @ 1.app.2e929560.js:2
t.cont @ 1.app.2e929560.js:2
h @ 1.app.2e929560.js:2
c @ 1.app.2e929560.js:2
g @ 1.app.2e929560.js:2
a @ 1.app.2e929560.js:2
t.cont @ 1.app.2e929560.js:2
h @ 1.app.2e929560.js:2
c @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
d @ 1.app.2e929560.js:2
g @ 1.app.2e929560.js:2
h @ 1.app.2e929560.js:2
P.<computed> @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
v @ 1.app.2e929560.js:2
h @ 1.app.2e929560.js:2
H @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
v @ 1.app.2e929560.js:2
h @ 1.app.2e929560.js:2
c @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
Promise.then (async)
i.then @ 1.app.2e929560.js:2
T @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
v @ 1.app.2e929560.js:2
h @ 1.app.2e929560.js:2
H @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
v @ 1.app.2e929560.js:2
h @ 1.app.2e929560.js:2
H @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
v @ 1.app.2e929560.js:2
P.<computed> @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
v @ 1.app.2e929560.js:2
h @ 1.app.2e929560.js:2
c @ 1.app.2e929560.js:2
s @ 1.app.2e929560.js:2
put @ 1.app.2e929560.js:2
t @ 1.app.2e929560.js:2
S.e.put @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
d @ 1.app.2e929560.js:2
g @ 1.app.2e929560.js:2
h @ 1.app.2e929560.js:2
S.c.put @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
onRemote @ 7.app.2e929560.js:1
u @ 1.app.2e929560.js:2
d @ 1.app.2e929560.js:2
(anonymous) @ 1.app.2e929560.js:2
b @ 1.app.2e929560.js:2
ut @ 1.app.2e929560.js:2
it @ 1.app.2e929560.js:2
ct @ 1.app.2e929560.js:2
ht @ 1.app.2e929560.js:2
N @ 1.app.2e929560.js:2
z @ 1.app.2e929560.js:2
Zt @ 1.app.2e929560.js:2
Jt @ 1.app.2e929560.js:2
t.unstable_runWithPriority @ 1.app.2e929560.js:2
Vo @ 1.app.2e929560.js:2
R @ 1.app.2e929560.js:2
Gt @ 1.app.2e929560.js:2
i @ 1.app.2e929560.js:2
Show 59 more frames
`

**Comment by igboyes** [comment]
This was caused by SSL problems that are a side effect of us using cx_freeze to bundle Virtool for distribution.

Virtool 4 will also be available as a Docker image from now on to avoid these issues.

https://github.com/virtool/virtool/pkgs/container/virtool
