### ISSUE TITLE
File size reduced when trying to upload sample files

### ISSUE THREAD

**Issue by CFearer** [virtool/virtool#2447]
Hello. Whenever I try to add a sample I receive an error that the read files are smaller than expected and I am missing the majority of my reads. However, the files are the normal size up to this point (see screen shots below). I’m not sure what could be going wrong?

Thanks!
Carrie

<img width="1159" alt="Screen Shot 2021-11-12 at 12 26 15 PM" src="https://user-images.githubusercontent.com/71893635/141509602-b7d56d95-0ac2-4c0a-a255-7e0bcb0574e3.png">
<img width="1156" alt="Screen Shot 2021-11-12 at 12 28 04 PM" src="https://user-images.githubusercontent.com/71893635/141509620-3c8b5ef9-b268-4b67-bb25-a3e5bc577c1c.png">
<img width="1060" alt="Screen Shot 2021-11-12 at 12 28 53 PM" src="https://user-images.githubusercontent.com/71893635/141509631-9759b8c4-53a1-4e7d-b968-89fb31d4fb9d.png">

**Comment by MikeERott** [comment]
Where are these files from? At 65KB, these are small files compared to what we normally work with or what Virtool expects. Normally HTS files are 500MB or larger
