### ISSUE TITLE
NuVs fails when creating a new directory

### ISSUE THREAD

**Issue by CFearer** [virtool/virtool#2492]
Hello. I have been running NuVs analyses for the past few weeks, but this morning I received the following error:

<img width="539" alt="Screen Shot 2021-12-17 at 9 18 47 AM" src="https://user-images.githubusercontent.com/71893635/146558777-7734325c-6c07-4b74-a2aa-61152040225c.png">

I’m not sure what the issue is?

Thanks!

**Comment by igboyes** [comment]
Hi @CFearer. My first guess with this is that the host machine running Virtool has lost access to the storage location.

Have you tried starting this analysis a second time?

**Comment by CFearer** [comment]
Yes, I’ve tried it several times and even today it is still giving me the error.

**Comment by igboyes** [comment]
I believe this is resolved. Please  re-open if this issue reoccurs.
