### ISSUE TITLE
Perpetual HMM loading still exists

### ISSUE THREAD

**Issue by maplexuci** [virtool/virtool#254]
I upgraded to Beta5.0 But the HMM perpetual loading still exists.

**Comment by igboyes** [comment]
1. First, can you go to the _Home_ page in Virtool and verify that the correct version (v2.0.0-beta.5) is properly installed.
2. Close and restart Virtool from the terminal.
3. Remove old profiles.hmm.
4. Refresh browser and reinstall official HMM data again.

Hope this works for you.

**Comment by maplexuci** [comment]
Still the same. When I refresh the browser under HMM tab, it shows 404 not found.
![screenshot from 2017-11-21 15 48 21](https://user-images.githubusercontent.com/8636318/33096017-91b4ce64-ced3-11e7-967b-565baba71a0f.png)

**Comment by igboyes** [comment]
Did you verify on the home page that you are running v2.0.0-beta.5?

**Comment by maplexuci** [comment]
Yes.
![screenshot from 2017-11-21 15 56 40](https://user-images.githubusercontent.com/8636318/33096343-96acb6ec-ced4-11e7-8bc0-466b6983afee.png)

**Comment by igboyes** [comment]
Okay. Found another problem. Thanks for bearing with me on this.

**Comment by igboyes** [comment]
I'm going to release beta.6 within the next hour. Can you manually download the ``virtool.tar.gz`` for that release from GitHub and copy its contents into your installation directory.

The updates were not installing properly which resulted in you not seeing the fixes I made. This issue is now cleared up I think.

**Comment by maplexuci** [comment]
Good to know. I will definitely do it tomorrow morning.

**Comment by maplexuci** [comment]
Now it's working perfectly! No problems in running "NuVs" analysis. Thanks.

**Comment by igboyes** [comment]
Excellent!
