### ISSUE TITLE
New error in auto-installing HMM under beta7.0

### ISSUE THREAD

**Issue by maplexuci** [virtool/virtool#266]
I am helping another lab to install the virtool. Beta7.0 was installed. But this error shows up when running automatic installation of HMM.
file:///home/shu/Pictures/Screenshot%20from%202017-11-27%2015:02:48.png
file:///home/shu/Pictures/Screenshot%20from%202017-11-27%2015:02:50.png

**Comment by igboyes** [comment]
Can't see your screenshots... 

I think I have already fixed this bug and the fix will be in beta8. This will be ready in the next hour or so.

**Comment by maplexuci** [comment]
Sure!

**Comment by igboyes** [comment]
#263

**Comment by igboyes** [comment]
Resolved in #267
