### ISSUE TITLE
"Ghost" job

### ISSUE THREAD

**Issue by maplexuci** [virtool/virtool#273]
#237 
Actually, the "ghost" under "Jobs" which shows consistent "waiting" in issue #237 is gone, however, the related "ghost" under "Subtraction" which is created at the same time is still there, showing "importing". Any way to remove that?
![screenshot from 2017-11-29 14 59 49](https://user-images.githubusercontent.com/8636318/33396546-d3558a86-d516-11e7-9133-0ff4d64f1984.png)

**Comment by igboyes** [comment]
Yes. That will be fixed before beta is finished.
