### ISSUE TITLE
docker assistance needed

### ISSUE THREAD

**Issue by Rooksie** [virtool/virtool#2769]
I am trying to use the dockerfile version of virtool and I have hit a roadblock.

I installed the Docker Desktop on my mac and then I ran the following command in terminal:
`docker pull ghcr.io/virtool/virtool:13.4.3`

I ran it a second time and see this
`$ docker pull ghcr.io/virtool/virtool:13.4.3`
`13.4.3: Pulling from virtool/virtool`
`Digest: sha256:d871d4ec6efc3bdf3d6ad7b538eedbddb2cd2e85cef7b07dec5aab88eec0c3d4`
`Status: Image is up to date for ghcr.io/virtool/virtool:13.4.3`
`ghcr.io/virtool/virtool:13.4.3`

I then ran the virtool image through the Docker Desktop application and I get this log output:
`2023-01-03 13:59:25 2023-01-03 18:59:25  cli         INFO     Starting in server mode`
`2023-01-03 13:59:25 2023-01-03 18:59:25  startup     INFO     Virtool 13.4.3`
`2023-01-03 13:59:25 2023-01-03 18:59:25  startup     INFO     Mode: server`
`2023-01-03 13:59:25 2023-01-03 18:59:25  startup     INFO     Starting HTTP client`
`2023-01-03 13:59:25 2023-01-03 18:59:25  connect     INFO     Connecting to MongoDB`
`2023-01-03 13:59:25 2023-01-03 18:59:25  utils       INFO     Connecting to PostgreSQL`
`2023-01-03 13:59:25 2023-01-03 18:59:25  redis       INFO     Connecting to Redis`
`2023-01-03 13:59:25 2023-01-03 18:59:25  utils       INFO     Connecting to OpenFGA`
`2023-01-03 13:59:25 2023-01-03 18:59:25  utils       INFO     Found OpenFGA openfga-sdk /0.0.1`
`2023-01-03 13:59:25 2023-01-03 18:59:25  utils       CRITICAL Could not connect`

I suspect I am missing something simple, but as I haven't found much virtool docker image help online, I am writing here for assistance. 

Also, this is my first time using docker.

Thank you

**Comment by igboyes** [comment]
Do you have accesss to a Linux computer?

I am not sure it is worth the effort to get Virtool working on MacOS as you will have major performance problems when when running the analysis workflows. Docker relies on features of Linux that have to be emulated with significant overhead to make things work.

How were you running Virtool prior to your attempt with Docker Desktop?

**Comment by Rooksie** [comment]
Okay, my hpc-admins came back that I can try using apptainer on our cluster to run a docker image.  Do you have any experience with that?

I tried apptainer's pull and run commands.  The pull looks good. It makes the container file (an sif).  When I try to run it I get that the run.py command is not in my home directory.  I am not running it from my home directory.

**Comment by Rooksie** [comment]
Still unable to figure out how to run virtool using the docker image. 

I cloned the compose github repository and went in to that directory. I then found docker-compose through python. And tried running it, I get:

`$ docker-compose -p virtool --profile test up -d`
`ERROR: The Compose file './docker-compose.yml' is invalid because:`
`services.mongo.environment.ALLOW_EMPTY_PASSWORD contains true, which is an invalid type, it should be a string,` `number, or a null`

**Comment by igboyes** [comment]
I have no experience with Apptainer. I think your HPC admins are best positioned to assist you in replicating our Docker deployment on that platform.

As [noted in the README](https://github.com/virtool/virtool#about-versions), you should be using the Virtool 4.0.0 versions. The only image available currently is `ghcr.io/virtool/virtool:v4.4.0-beta.1`.

If you provide this Docker Compose to your admins, they should be able to get things running for you.
```
version: "3.1"
services:
   mongo:
     image: mongo:3.6
      ports:
         - "27017:27017"
      volumes:
         - mongo:/data/db
   virtool:
      image: ghcr.io/virtool/virtool:v4.4.0-beta.1
      environment:
         VT_DATA_PATH: "/data"
         VT_HOST: "0.0.0.0"
      ports:
         - "9950:9950"
      volumes:
         - virtool:/data
```

**Comment by Rooksie** [comment]
Thank you! We figured out a workaround.  I have a virtool docker image running, but I am seeing some weird behavior and now I can't find where the image/container location was created, the virtool 'data' directory. I tried designating my "home" directory as the path for 'data', but is says "Could not locate or create directory".

Is there a way I can designate this location and/or be able to check it?

**Comment by igboyes** [comment]
If you are using the above Compose YAML, Docker [Volumes](https://docs.docker.com/storage/volumes/) will be created (`mongo`, `virtool`) to store persistent data.

Volumes are not accessible outside of Docker on the host system, which is generally not a problem as you should not need to access Virtool's data directory. Modifying its contents can corrupt your Virtool instance.

>weird behavior

If you give me more details on this and your environment, I can help more. Is MongoDB in a container or on the host, are you using Compose, etc?

**Comment by Commifreak** [comment]
I dont know if Iam having the same issue, but `image: ghcr.io/virtool/virtool:4.3.3` from the docs is giving me `Error response from daemon: manifest unknown`. The only one tag for v4 is v4.4.0-beta.1.

How to setup in docker?
