### ISSUE TITLE
"Create Subtraction" window doesn't go away after clicking "Start"

### ISSUE THREAD

**Issue by maplexuci** [virtool/virtool#294]
Like the screenshot, you need to click somewhere else outside of the small window to let it go. 

In addition, the words are overlapped in this window, anyway to make them clearly separated?

![screenshot from 2017-12-04 17 19 46](https://user-images.githubusercontent.com/8636318/33579369-9b5d9740-d917-11e7-9db1-f20c08f9433e.png)

**Comment by igboyes** [comment]
- [ ] fix overlap
- [ ] fix ``onHide`` bug
