### ISSUE TITLE
Implement pagination in jobs view

### ISSUE THREAD

**Issue by maplexuci** [virtool/virtool#298]
Created several samples, but no new jobs shows up in the "Job" tab. How to view jobs on different pages.

Also, a error came up. Not sure where does it from.

![screenshot from 2017-12-05 15 29 42](https://user-images.githubusercontent.com/8636318/33629343-b9661b26-d9d1-11e7-8f58-2ca09e53d2f5.png)
![screenshot from 2017-12-05 15 30 03](https://user-images.githubusercontent.com/8636318/33629379-d7dfa702-d9d1-11e7-82f6-43dfe18966bb.png)
![screenshot from 2017-12-05 15 30 07](https://user-images.githubusercontent.com/8636318/33629380-d7ead276-d9d1-11e7-944e-79889c575905.png)

**Comment by igboyes** [comment]
I'll add page numbers to the job list. You can clear complete and/or failed jobs by clicking the trash can or its drop down menu options.

The terminal error is described in #170.

**Comment by igboyes** [comment]
By the way the terminal error is essentially benign. It is just annoying.
