### ISSUE TITLE
Error on clicking the in progress analysis

### ISSUE THREAD

**Issue by maplexuci** [virtool/virtool#299]
Another error after creating the new analysis and click either one on the "in progress" page. But the analysis can be finished.

![screenshot from 2017-12-05 15 38 27](https://user-images.githubusercontent.com/8636318/33629569-83306cd6-d9d2-11e7-9862-b5e11be284b1.png)
![screenshot from 2017-12-05 15 36 33](https://user-images.githubusercontent.com/8636318/33629532-61a5ead2-d9d2-11e7-9274-a26d8a17e3a6.png)
![screenshot from 2017-12-05 15 36 35](https://user-images.githubusercontent.com/8636318/33629533-61b02272-d9d2-11e7-8e01-6e1b16f93e0c.png)

**Comment by igboyes** [comment]
Clicking should be disabled. I'll disable those button for in-progress analyses.
