### ISSUE TITLE
SubprocessError: Command failed: spades.py...

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#325]
```
Traceback (most recent call last):
File "/home/travis/build/virtool/virtool/virtool/job.py", line 112, in run
File "/home/travis/build/virtool/virtool/virtool/sample_analysis.py", line 942, in assemble
File "/home/travis/build/virtool/virtool/virtool/job.py", line 201, in run_subprocess
SubprocessError: Command failed: spades.py -t 7 -m 15 -1 data/samples/2df0edab/analysis/vakronym/unmapped_1.fq -2 data/samples/2df0edab/analysis/vakronym/unmapped_2.fq -o /tmp/tmppbjxkm_c -k 21,33,55,75. Check job log.
```

**Comment by maplexuci** [comment]
How should I provide you the FASTQ files that cause this issue? Via Dropbox or any other way you prefer?

**Comment by igboyes** [comment]
Dropbox would be perfect. Thanks a lot. This is a big help since we have not been able to reproduce this issue in any of our libraries.

**Comment by igboyes** [comment]
Thanks for the data. I am currently trying to reproduce the error. It is taking some time, but seems to be stable while SPAdes is running.

In the meantime, can you confirm with me which version of SPAdes you are using. There may be an issue with older versions of SPAdes. You check in the terminal using:

```bash
spades.py --version
```

**Comment by igboyes** [comment]
Thanks. I have reproduced the bug and it is unrelated to SPAdes version.

**Comment by igboyes** [comment]
@maplexuci 

I have fixed a few issues that were contributing to this problem.

I am still running into issues with your library. These are down to high memory usage by SPAdes, the assembler used in NuVs. The assembly fails because the memory limits set in _Settings_ > _Jobs_ are exceeded.

Once **v2.2.1** is released, try setting the NuVs memory values as high as possible and rerun your analysis. If you still run into a SPAdes error, there is not much that can be done outside upgrading your system RAM.

**Comment by maplexuci** [comment]
Good to know. Thanks.

**Comment by Commifreak** [comment]
Hi,

excuze me - but where is "Settings > Jobs" located? I dont find such sites inside the web-ui? I have the exact error with Virtool  3.9.8. Server has 32GB RAM.

```
Traceback (most recent call last):
File "/drone/src/virtool/jobs/job.py", line 166, in run
File "/drone/src/virtool/jobs/nuvs.py", line 149, in assemble
File "/drone/src/virtool/jobs/job.py", line 261, in run_subprocess

SubprocessError: Command failed: spades.py -t 7 -m 16 -1 data/samples/beiwqxfz/analysis/qqpv5fif/unmapped_1.fq -2 data/samples/beiwqxfz/analysis/qqpv5fif/unmapped_2.fq -o /tmp/tmpq1d4paar -k 21,33,55,75. Check job log.
```

**Comment by igboyes** [comment]
The job resource settings can no longer be set from the web interface as of v3.0.0. Please see https://www.virtool.ca/docs/manual/gs_configuration/#resources

**Comment by Commifreak** [comment]
Is it enough to set `mem`?

Gruß,
R. Kluth

**Comment by igboyes** [comment]
You should:

1. Set `mem` to the GB you available on your host machine
2. Since you are having memory issues with SPAdes, I would suggest setting `lg_mem` = `mem`

This will result in only one large job running at a time and using the full available memory. It would be a good idea to maximize `lg_proc` in this case too.

Another relevant issue: #1828.
