### ISSUE TITLE
Subtraction files can not be uploaded properly (only in v2.0.3)

### ISSUE THREAD

**Issue by maplexuci** [virtool/virtool#338]
Progress bar not moving. Files not show up or show up after refresh but not the right size (e.g. only shows 6Mb for a 130Mb genome). No error message.

**Comment by maplexuci** [comment]
Uploading of the fastq files also has the same issue

**Comment by igboyes** [comment]
There is a new ``upload_file`` permission. You should be able to add this permission to any existing accounts in the users section of the administrative interface.

In v2.0.4, the following UI will show up if you the account is not permitted to upload files.

![image](https://user-images.githubusercontent.com/5943558/35539342-010fab72-0506-11e8-917a-6c461820492e.png)

**Comment by maplexuci** [comment]
I have this upload_file permission. Still can not upload the files.

**Comment by maplexuci** [comment]
Good to know. I haven’t noticed that the v2.0.4 is released. I will try it tomorrow. Thanks.

**Comment by igboyes** [comment]
Have you had a chance to check if this fixes your issue?

**Comment by maplexuci** [comment]
I am check it now. It's working fine with file upload now.

**Comment by igboyes** [comment]
Cool. Thanks.

**Comment by maplexuci** [comment]
I found another issue. I will post it in a separate one.
