### ISSUE TITLE
Allow Virtool to use proxy servers

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#341]

**Comment by LucasvdGouw** [comment]
We have an internal network and the only way to connect to the Internet is through a proxy server.

**Comment by igboyes** [comment]
It shouldn't be too difficult for us to make Virtool capable of making requests through a proxy server.

If this might work for you, we can prioritise this issue.

**Comment by igboyes** [comment]
Prototype of settings UI

![image](https://user-images.githubusercontent.com/5943558/35752814-2bc23ede-0812-11e8-8470-9be3d059d5fa.png)

**Comment by LucasvdGouw** [comment]
sorry for the wait.

Yes that would be lovely.
