### ISSUE TITLE
Download the genome coverage image

### ISSUE THREAD

**Issue by maplexuci** [virtool/virtool#366]
Is there any way that the genome coverage image can be downloaded or copied except the screen shot?

**Comment by igboyes** [comment]
Not at the moment. This might be part of #15, an issue describing report printing support.

For now, it might be possible to make just the image downloadable as an SVG file.

Any suggestions?

**Comment by igboyes** [comment]
@Miminko 

For now we will make the charts downloadable as either SVG or PNG/JPEG.

We can talk about the approach for doing this later. Here are some references:

[Gist for PNG download](https://gist.github.com/vicapow/758fce6aa4c5195d24be)
[Library for SVG download](https://www.npmjs.com/package/d3-save-svg)
