### ISSUE TITLE
Synchronize Pathoscope chart scrolling

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#367]
Make all Pathoscope coverage charts for a given virus scroll in unison when only one isolate's scroll bar is moved.

The code to do this is already present (see `Pathoscope/Isolate.js`), but is not working due to a regression.

```javascript
componentDidMount () {
    this.chartNode.addEventListener("scroll", this.handleScroll);
}

componentWillUnmount () {
    this.chartNode.removeEventListener("scroll", this.handleScroll);
}
```

**Comment by Miminko** [comment]
Working for now!
