### ISSUE TITLE
Incomplete installation instructions

### ISSUE THREAD

**Issue by eburgueno** [virtool/virtool#368]
The official [documentation](https://docs.virtool.ca/getting-started/installation.html) seems to suggest that getting virtool going is as simple as downloading and running `nohup ./run &`. This is most definitely not the case:

```
$ curl --silent -L -o virtool-2.0.3.tar.gz https://github.com/virtool/virtool/archive/v2.0.3.tar.gz
$ tar -xzf virtool-2.0.3.tar.gz
$ cd virtool-2.0.3
$ ls
LICENSE  assets  bandit.yml  client  contributors.txt  readme.md  requirements.txt  run.py  setup.py  templates  tests  virtool
```

The instructions seem to assume a a great deal about the environment the admin should provide, and none of these dependencies are documented. The `run.py` script is also missing a shebang line:
```
$ ./run.py 
./run.py: line 1: import: command not found
./run.py: line 2: import: command not found
./run.py: line 3: import: command not found
./run.py: line 4: import: command not found
./run.py: line 5: import: command not found
./run.py: line 6: import: command not found
./run.py: line 7: import: command not found
./run.py: line 9: from: command not found
./run.py: line 10: from: command not found
./run.py: line 11: from: command not found
./run.py: line 12: from: command not found
./run.py: line 14: sys.dont_write_bytecode: command not found
./run.py: line 16: syntax error near unexpected token `('
./run.py: line 16: `logger = logging.getLogger("aiohttp.server")'

$ sudo apt-get -y install python
$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from cx_Freeze import setup, Executable
ImportError: No module named cx_Freeze

$ sudo apt-get -y install python-pip zlib1g-devel
$ pip install cx_Freeze
$ python setup.py install
running install
running build
running build_exe
Traceback (most recent call last):
  File "setup.py", line 34, in <module>
    executables=executables)
  File "/usr/local/lib/python2.7/dist-packages/cx_Freeze/dist.py", line 349, in setup
    distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
    self.run_command('build')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/cx_Freeze/dist.py", line 219, in run
    freezer.Freeze()
  File "/usr/local/lib/python2.7/dist-packages/cx_Freeze/freezer.py", line 616, in Freeze
    self.finder = self._GetModuleFinder()
  File "/usr/local/lib/python2.7/dist-packages/cx_Freeze/freezer.py", line 342, in _GetModuleFinder
    finder.IncludePackage(name)
  File "/usr/local/lib/python2.7/dist-packages/cx_Freeze/finder.py", line 659, in IncludePackage
    module = self._ImportModule(name, deferredImports)
  File "/usr/local/lib/python2.7/dist-packages/cx_Freeze/finder.py", line 351, in _ImportModule
    raise ImportError("No module named %r" % name)
ImportError: No module named 'uvloop'

$ pip install -r requirements.txt
(...)
Collecting async-timeout==2.0.0 (from -r requirements.txt (line 6))
  Downloading async-timeout-2.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Z0cfaM/async-timeout/setup.py", line 1, in <module>
        import pathlib
    ImportError: No module named pathlib
$ sudo apt-get -y install python-pathlib
$ pip install -r requirements.txt
(...)
Collecting pytest-asyncio==0.8.0 (from -r requirements.txt (line 33))
  Downloading pytest-asyncio-0.8.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-uOlGpF/pytest-asyncio/setup.py", line 19, in <module>
        version=find_version(),
      File "/tmp/pip-build-uOlGpF/pytest-asyncio/setup.py", line 8, in find_version
        version_file = Path(__file__).parent.joinpath('pytest_asyncio', '__init__.py').read_text()
    AttributeError: 'PosixPath' object has no attribute 'read_text'
```

I could keep going trying to figure out the dependencies myself, but I strongly feel this is not the best approach; particularly when these [keep changing](https://github.com/virtool/virtool/commits/master/requirements.txt) between releases.

Are there any plans to improve the documentation for a standalone install?

**Comment by igboyes** [comment]
I'm sorry you're having issues with the documentation. I assure you it _should_ be as easy to get started as described in the docs.

Your difficulties are the result of downloading the source archive from GitHub instead of the built asset `virtool.tar.gz`. This is why the archive and executable file names in your posted output do not match those described in the documentation. To avoid future confusion, I've modified the documentation to direct users to our website to download the release asset and eliminated mention of GitHub.

Make sure you are downloading the built asset `virtool.tar.gz` from either the [Virtool website](https://www.virtool.ca/downloads/) or from GitHub:

![image](https://user-images.githubusercontent.com/5943558/36112244-db4c6d3e-0fdd-11e8-9f2c-a4e6a4ae32f2.png)

I'd welcome any specific suggestions you have towards making this part of the documentation clearer.

**Comment by eburgueno** [comment]
Hi @igboyes, thank you for your help. Indeed, I was downloading the source code instead of the built asset. This one is indeed self-contained so the issues I had are no longer.

Thank you also for updating the docs. I misread the URL on the official download page and thought it was the same as the source tar.gz on GitHub, so I went and downloaded that instead.

My only two other suggestions would be
1. Make a comment about `./run -h` for the additional options available
2. Document the build instructions somewhere (not everyone will want to run pre-built binaries in production).

I will try and get Virtool containerised with Docker. Happy to share the Dockerfile if that is of interest.

**Comment by igboyes** [comment]
@eburgueno 

It would be greatly appreciated if you would share your Dockerfile. It is in the todo queue, but there are other priorities. I am also a Docker amateur.

Thank you for the documentation suggestions. I'll prioritise build instructions.
