### ISSUE TITLE
Prevent analysis before virus database rebuild

### ISSUE THREAD

**Issue by Miminko** [virtool/virtool#371]

**Comment by igboyes** [comment]
#### Server
- [ ] reject requests before database is built
- [ ] update documentation

#### Client
- [ ] disable analysis button
- [ ] show message with link to rebuild index

**Comment by igboyes** [comment]
Sorry, I wasn't clear on this.

The message and disabled button should only be applied when there are no "ready" indexes available. I can think of three cases.

1. No indexes built or currently building
    - indexes list length is zero
    - disable button
    - show warning message similar to what you have already developed
2. Indexes available but not ready
    - index array length is not zero
    - none of the index objects have `ready` set to `true`
    - disable button
    - show more positive message (not warning) that an index build is in progress
3. Indexes available and ready
    - at least one index object has `ready` set to `true`
    - button enabled
    - no message
