### ISSUE TITLE
Minor UI problems

### ISSUE THREAD

**Issue by Miminko** [virtool/virtool#414]
- resizing the window so that the navbar icons on the right are forced under the navigation tabs extends the height of the nav menu, overlapping the headers of the main body
- this also causes the account icon drop-down menu to be overlapped by the delete icon in the Jobs tab
- For pathoscope bowtie analysis samples: expanding and collapsing virus charts when the window scroll view is not at the top results in an animation delay that overlaps the table and toolbar above 
(does not occur in NuV analyses)

**Comment by igboyes** [comment]
Thanks for documenting this. I'm splitting your issue into two new ones:

#418 
#419
