### ISSUE TITLE
Client side validation of password length

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#421]
In password change forms, make sure the password meets the minimum length requirement (`minimum_password_length`) in the settings store.

This will be enforced by the API in the `v2.1.0` release.

Don't validate login form or old password verification inputs.

**Comment by Miminko** [comment]
I had already added this feature  to the #404 pull request. Should I separate it into two?

**Comment by igboyes** [comment]
Does it validate based on the `minimum_password_length` setting? If so, that's perfect.

**Comment by Miminko** [comment]
Yes.
