### ISSUE TITLE
Validate API key name length during creation

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#434]
Make API key name a required field during validation.

Validation is already done at API, but this will save a request.

**Comment by Miminko** [comment]
- Are accounts limited to creating only one key? I can only create one. 
- Should there be a UI feedback for when you successfully update the API key permissions?

**Comment by Miminko** [comment]
clicking on create shows the API key saying it will not be shown again, but clicking the button shows this modal as many times as you want.
