### ISSUE TITLE
Job resource settings errors

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#474]
Show input errors when:
- values in **Resources Limits** section exceed real limits
- values in **Task-specific Limits** section exceed values in **Resource Limits** section

Real values can be found at `GET http://localhost:9950/api/resources` .
```json
{
    "proc": [
        65.4,
        64.4,
        65.7,
        65.5,
        64.2,
        64.1,
        65.0,
        64.7,
        64.5,
        64.4,
        64.6,
        63.5
    ],
    "mem": {
        "total": 33627844608,
        "available": 23943528448
    }
}
```

The hard limit for `proc` is the length of the `proc` array in the response body.

The hard limit for `mem` is the `mem.total` value in the response body.

There is no backend validation of these values at the moment.

**Comment by Miminko** [comment]
- is mem.total in bytes? 
therefore this example has ~31GB?
- is this GB value calculated for the value of mem in /api/settings/data beforehand or is it fixed at 16GB?

**Comment by Miminko** [comment]
I get strange behavior when updating the CPU and Memory Limits. Individually they update fine, but when updating one after the other the least recent change seems to get overwritten by the default values of proc = 8 and mem = 16.

**Comment by Miminko** [comment]
- Changing multiple fields in task-specific limits also overwrites changes with default values.
- memory limit accepts float values (one decimal point) but will only save the floored integer equivalent.

**Comment by igboyes** [comment]
Prevent shift down on error in resource limits inputs

Hard limit on min resource limit values. Going lower than minimum value locks input at minimum value

Resources limits cannot go below locked task-specific limit values.

Backspace on Task-specific input field shows 0 instead of empty input

Task-specific limits can't be zero.
