### ISSUE TITLE
Non-functional remove job icon

### ISSUE THREAD

**Issue by Miminko** [virtool/virtool#516]
Currently the remove icon on a job detail page is non-functional; it simply prints the detail.id to the console.
line 86:    onClick={() => window.console.log(detail.id)}

Should either:
- add job removal functionality in which deletion also results in navigating back to the jobs tab, or 
- remove the icon so job deletion is done solely through the 'clear jobs' button in the jobs tab.

**Comment by igboyes** [comment]
Go with option one please!
