### ISSUE TITLE
Unable to download HMMs

### ISSUE THREAD

**Issue by LucasvdGouw** [virtool/virtool#521]
When trying to download HMMs, the progress bar does not move. Though a proxy has been set. it seems unable to connect.

**Comment by igboyes** [comment]
Can you confirm that when you visit _Settings_ > _Updates_, you are able to see either the next available update or a message readying "Software is up-to-date".

This will not work if the proxy connection is broken.

**Comment by LucasvdGouw** [comment]
The Settings>update tab will not even load

**Comment by igboyes** [comment]
If you are not using v2.2.1, you should upgrade by copying the content of `virtool.tar.gz` [release file](https://github.com/virtool/virtool/releases/tag/v2.2.1) to your install directory and restarting the server. There were some issues with retaining the proxy settings correctly.

If this does not solve the problem, can you give me more detail on how you have the proxy configured. I am not able to reproduce your issue using a proxy server during testing.
