### ISSUE TITLE
Deprecate administrator group in client

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#548]
- group administrator-related components in group editor ui
- replace checks for administrator group membership with having `adminstrator` set `true`
- replace checks for `manage_users` and `modify_settings` permissions with having `administrator` set `true`

**Comment by Miminko** [comment]
For adding users to groups, should the request change from `POST /api/users/:userId/groups` to `PATCH /api/users/:userId`? For the latter though, how would I append to the groups array instead of overwriting it?

**Comment by igboyes** [comment]
Yes.

The intention is that the groups array is overwritten, similarly to how we implemented virus schema updates.

**Comment by Miminko** [comment]
Are there possible situations that require `administrator` set to `true` but certain fields in `permissions` are set to `false`? Or can I assume that if `administrator: true` then all permissions are automatically `true`?

**Comment by igboyes** [comment]
Yes, `administrator` trumps all permissions.
