### ISSUE TITLE
Reference creation modal

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#578]
Extend the reference creation modal with the following fields from the API docs:

| Name        | Type    | Optional | Description                                                                                        |
| :---------- | :------ | :------- | :------------------------------------------------------------------------------------------------- |
| name        | string  | False    | the virus name                                                                                     |
| description | string  | True     | a longer description for the reference                                                             |
| data_type   | string  | False    | the sequence data type (only _genome_ is currently supported)                                      |
| organism    | string  | True     | the sequence data type (only _genome_ is currently supported)                                      |
| public      | boolean | True     | make the reference viewable and usable by all users (default=`False`)                              |

#### `description`

Use a `textarea` element for this.

#### `data_type`

Use a `select` type input element. Initially it will only have one option: _genome_.

#### `public`

Use a checkbox for this. Should be unchecked by default.

**Comment by Miminko** [comment]
- Is there a maximum number of references that can be saved? When I try to create more than 15 references, the state.found_count & state.total_count are reflecting the total number created correctly but the state.documents array only ever returns 15 items, with newer entries seemingly overwriting older entries. 
- created reference entries don't seem to be added into the documents array in any predictable order; i.e. newly created references can be inserted anywhere in the array regardless of creation date, name, id, etc.
- does the reference API support deletion / updating of references?

**Comment by igboyes** [comment]
1. The `/api/references` endpoint supports the `per_page` and `page` parameters like the endpoints for document types.
2. The array returned by the API is sorted by name. We can discuss changing this.
3. Not yet.

**Comment by igboyes** [comment]
This looks functionally finished to me.
