### ISSUE TITLE
Import reference client interface

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#589]
#### UI

Display a form similar to the reference creation form. It should include a file selection input.

When the user submits the form, a progress bar should be displayed showing the progress of the upload and then the progress of the import process. Text below the progress bar should indicate the current step.

#### Uploading

Upload a file to the `/uploads/kinds` endpoint.

The progress of the upload should be tracked on the client using the `progress` event from `superagent`. The first `0.4` (or so) of the progress bar will track the upload.

Once the upload is complete a JSON response will be returned by the server. This will include an `id` field, which is the unique identifier for the file.

#### Importing

The import request is made to `POST /api/refs` in the same way as creating an empty reference.

Use the file `id` previously received from the server as the value for the `import_from` property in the request payload.

The request should return almost immediately. A background process is spawned to deal with the long running task of actually importing the file. The process can be retrieved from the server periodically to update any client UI that indicates the progress of the process.

A reference to the process is included in the JSON response from the reference import request:
```json
{
    "process": {
        "id": "foobar"
    }
}
```

**Comment by Miminko** [comment]
- should the import only allow one file to import per reference? or can references have multiple files associated with it?
- should the import modal list already uploaded files? with/without scroll?

**Comment by igboyes** [comment]
1. Only one file.
2. No. The file uploaded in the import modal is the only file that should be used.

**Comment by Miminko** [comment]
- should there be a way to cancel uploads if the import modal is exited? or prevent the modal from exiting for the duration of the upload?

**Comment by igboyes** [comment]
Hmm. I think locking the modal opening while the upload is in progress is probably the best option at the moment.

**Comment by Miminko** [comment]
I'm getting a `POST http://localhost:9950/api/refs 422 (Unprocessable Entity)` when I try to import a reference by creating a new reference with `import_from` set to the file id returned from the server.
The error response:
`errors: {name: ["required field"]}`

**Comment by igboyes** [comment]
Are you passing a value for the reference `name`? It is a required field.
