### ISSUE TITLE
Reference removal button

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#590]
Reference removal is supported by the API in the latest `v3.0.0` branch. It works in the same way as a lot of the other removal endpoints.

```DELETE /api/refs/:ref_id```

Removal actually takes some time, so a background process is started and progress can be tracked. As a consequence `204 No content` is not returned as the respose status header. Instead `202 Accepted` is returned with a reference in the response body and header to the process.

For now, let's not indicate to the user that there is a background process. Just immediately remove the reference when the request completes.

There is also documentation in the latest `v3` branch of the documentation.

**Comment by Miminko** [comment]
Currently results in `DELETE http://localhost:9950/api/refs/nh86ypw8 404 (Not Found)` error
