### ISSUE TITLE
Refresh references after creating a new one

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#591]

**Comment by Miminko** [comment]
I'm getting a `POST http://localhost:9950/api/refs 403 (Forbidden)` error on the latest branch when I try to create new references

**Comment by igboyes** [comment]
This is a bug. Thanks. #600 

Can you give yourself the `create_ref` permission for now? That should fix the issue.

**Comment by igboyes** [comment]
#600 is resolved by the way so you should not be getting `403` anymore.
