### ISSUE TITLE
React Helmet

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#610]
The [react-helmet](https://github.com/nfl/react-helmet) library is used to configure HTML **title** tags in React components.

It is implemented sporadically in Virtool and needs to be fully utilized. Start by adding titles for main views:

- Home
  should remain just `Virtool`

- _References_
  `References - Virtool` (or use · or •)

- Specific resources (eg. an OTU) should use their display name
  `Tobacco mosaic virus - References - Virtool`

Discuss most complicated or ambiguous cases in this issue.

**Comment by Miminko** [comment]
Should the titles just be within the html head only, or should it also be visible in the UI as well?
