### ISSUE TITLE
 Overhaul RemoveReferenceTask

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#622]
Currently, this task is spawned after a user triggers deletion of a **specific** entire reference. It removes associated:
- Indexes
- Unreferenced OTUs (not referenced in any analysis)
- Referenced OTUs (safely removed with history that allow them to still be referenced in analyses)

# Develop Periodic Task Framework
Develop a system for spawning a fresh task at a given interval. Idea:
```python
# Call this in virtool.startup
spawn_periodically(scheduler, task, interval)
```

Discuss ideas after thinking about this.

# Convert to Generic Task
Allow the `RemoveReferenceTask` task to be regularly spawned to clean-up lingering data from non-existent references. It will still be spawned after deleting a specific reference.

OTUs and sequences are not completely removed if the server is stopped while the reference removal job is in progress. Regularly running the task will solve this problem.

# Enhancements
- make sure the reference directory has been completely removed
- remove all index documents associated with non-existent references (`reference.id` field)
- remove all unreferenced OTUs with non-existent `reference.id` values
  - extend existing `remove_unreferenced_otus` method
  - OTUs have a `reference.id` field
- safely remove all referenced OTUs with non-existent `reference.id` values
  - extend existing `remove_referenced_otus` method
- remove unreferenced history
  - current task only removes OTUs and indexes
  - use unreferenced OTU ID list from previous step?
  - remove when `otu.id` is not a referenced OTU
  - history has `reference.id` field

**Comment by tianshengsui** [comment]
> - remove unreferenced history
>      - current task only removes OTUs and indexes
>      - use unreferenced OTU ID list from previous step?
>      - remove when otu.id is not a referenced OTU
>      - history has reference.id field

@igboyes I think current task already remove unreferenced history in `remove_unreferenced_otus` step:
https://github.com/virtool/virtool/blob/a410e8f68b8d0897eb5741d0b008c989be73ee82/virtool/references/db.py#L277
