### ISSUE TITLE
Definitions of 'Best Hit' and 'Weight' 

### ISSUE THREAD

**Issue by joneill4x** [virtool/virtool#628]
Is it possible for someone to give me the strict definitions for the 'Best Hit' and 'Weight' variables seen in the Pathoscope results?  I can't find them in the docs or anywhere.  Thank you, Joe.

**Comment by igboyes** [comment]
**Weight**
The proportion of reads mapped to the virus, isolate, or sequence. For multi-mapping reads, the value of a read is distributed proportionately to its most likely source genomes.

**Best Hit**
The proportion of reads that have their highest scoring mapping to the virus, isolate, or sequence. We find that this value is not used much in practice.

---

Virtool uses the Pathoscope algorithm for reassigning weight of ambiguous reads to their most likely source genomes. The Pathoscope report values in the web interface are derived from the [output of the Pathoscope package](https://github.com/PathoScope/PathoScope#2-output-tsv-file-format).

The Virtool *weight* value maps to *Final Guess* in Pathoscope and *best hit* maps to *Final Best Hit*.
