### ISSUE TITLE
Account Create API Key

### ISSUE THREAD

**Issue by Miminko** [virtool/virtool#638]
- the Create API Key modal and the detail view of API Keys are missing the checkmark icons for permission fields.
- After successful API creation a different modal containing the API Key information is displayed, yet after closing this modal the user can see a brief animation of the previous Create API Key modal transitioning out. 
- Update API Key button disabled

**Comment by igboyes** [comment]
Moved first problem to separate issue (#671):
> - the Create API Key modal and the detail view of API Keys are missing the checkmark icons for permission fields.
