### ISSUE TITLE
Group Modifications

### ISSUE THREAD

**Issue by Miminko** [virtool/virtool#639]
- Deleting groups that contain members results in a `DELETE http://localhost:9950/api/groups/:groupid 500 (Internal Server Error)`. On page reload the group seems to be successfully deleted.
- Modifying a permission field for a group not at the top of the group listing order results in the Group modal refresh that transfers the focus to whichever group is at the top of the list.

**Comment by igboyes** [comment]
Sentry issue: [SERVER-AN](https://sentry.io/cph/server/issues/543970309/)
