### ISSUE TITLE
References' global Settings

### ISSUE THREAD

**Issue by Miminko** [virtool/virtool#640]
- deleting a preset source type + page reload results in a `500 (Internal Server Error)`, with subsequent page reloads show successful deletion.

**Comment by igboyes** [comment]
I have started a PR (#651) that should hopefully fix this issue.

**Comment by igboyes** [comment]
Is this still happening @Miminko?

**Comment by Miminko** [comment]
Currently there isn't an option to remove preset source types anymore, but both the global settings source types and the reference-specific settings source types are synchronized as they both rely on the `state.references.detail.restrict_source_types` value. 

Perhaps the global settings should rely on a `restrict_source_types` value under `state.settings`? And that value will be used as the default that can be changed for each reference?

**Comment by igboyes** [comment]
Will be dealt with in #685
