### ISSUE TITLE
Schema Drag and Drop

### ISSUE THREAD

**Issue by Miminko** [virtool/virtool#676]
Currently Schema's segments array relies on the `react-beautiful-dnd` library to render an interactive list. After updating the `react-beautiful-dnd` and `react` libraries the drag and drop feature seems to be broken.

**Comment by igboyes** [comment]
I'm thinking we should drop this an use something simpler like [react-dnd](https://react-dnd.github.io/react-dnd/examples-sortable-simple.html).

**Comment by igboyes** [comment]
Fixed `react-beautiful-dnd`.
