### ISSUE TITLE
Reference indexes user interface

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#690]
Get this working again.

- retrofit old client code
- for unbuilt changes shown in creation modal, show only first 10-15 and then something like _+123_ or _123 more..._

**Comment by Miminko** [comment]
Currently it seems to be able to rebuild the first and only existing index, but not be able to process building an index for newly created references. I get a `POST http://localhost:9950/api/refs/w9wem1z1/indexes 500 (Internal Server Error)` for new reference index builds, but not for existing index rebuilds, after PR #692

**Comment by igboyes** [comment]
Thanks. I will fix this. #695
