### ISSUE TITLE
Reference cloning & importing

### ISSUE THREAD

**Issue by Miminko** [virtool/virtool#716]
- Cloning a reference relies on data in the `state.references.documents` array to fill in fields of the modal with data from target reference. Currently missing the `description` property. 
- `POST /api/refs` with request data containing the `clone_from: refId` field simply creates another reference without cloning the OTU data.
- Attempting to import non-reference/invalid files for a new reference results in the creation of a reference  card with a process that does not progress.

**Comment by igboyes** [comment]
1. Don't autofill the description field.
2. No it doesn't. The `clone_from` value being provided to `Request.send()` in your request is `undefined` and is being dropped from the body by `superagent`.
3. Thanks. #718
