### ISSUE TITLE
Rebuild Index

### ISSUE THREAD

**Issue by Miminko** [virtool/virtool#717]
Rebuilding the index currently does not update the `latest_build` data.

**Comment by igboyes** [comment]
Does refreshing the page update the data?

**Comment by Miminko** [comment]
No :(

**Comment by Miminko** [comment]
I'm also getting weird behaviour when I navigate back and forth from index detail pages to the index list, some index entries seem to disappear/reappear

**Comment by igboyes** [comment]
Okay. Let me know what you find.

**Comment by Miminko** [comment]
I think it's due to the getIndex request, which gets the index detail data from `/api/indexes/:indexVersion`, which only stores the newest entry for that version number. So if I had two references each with an index at version 0, the most recently created index will be retrieved for both?
Is there another way to retrieve specific index data by index id?

**Comment by igboyes** [comment]
`GET /api/indexes/:index_id` will work. This is an oversight for me since index versions are no longer unique.

**Comment by igboyes** [comment]
I will stop accepting index versions at that endpoint (#723).
