### ISSUE TITLE
Render created_at and user values in ViewHeader

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#735]
Currently, the `created_at` date and `id` of the creating user are shown in tables in detail pages. This is hard to read and is also not implement consistently:

![image](https://user-images.githubusercontent.com/5943558/40628767-b7add340-627b-11e8-9e4d-d9f0a8420300.png)

![image](https://user-images.githubusercontent.com/5943558/40628772-c58948dc-627b-11e8-9a54-0bce8c110b6f.png)

Standardize the rendering of the this data as small-styled text below the `<ViewHeader />` title.

It may make sense to add a margin below the `<ViewHeader />` so the page is not too cramped.

**Also remove `<PageHint />` component**

**Comment by Miminko** [comment]
@igboyes 
I currently have ViewHeader so that the `<PageHint />` component is optional, thinking it can be removed later when the scrolling pagination is implemented.
Should I just completely remove it now?

**Comment by igboyes** [comment]
No. Let's just leave it for now. Good work!
