### ISSUE TITLE
Remote reference creation UI

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#736]
**Only the [official reference](https://github.com/virtool/virtool-database) will be supported as a remote reference at the release of v3.0.0.**

As a result, it is not necessary to include a form for creating a remote reference. I removed this client code in #730. Linking the official remote reference will be a one-click action. I am thinking something like this a starting point:

![screenshot from 2018-05-28 13-50-34](https://user-images.githubusercontent.com/5943558/40629280-f1415598-627e-11e8-89b8-0ff0e813a906.png)

**Comment by igboyes** [comment]
Docs updated in https://github.com/virtool/virtool-website/commit/32a248941529d081659c1ca7fe51bc8f71ef0a43

**Comment by Miminko** [comment]
Currently the `state.references.documents` array gets updated after the remote reference is finished importing rather than when it first starts; therefore the newly created remote reference does not display to UI to show loading progress.
