### ISSUE TITLE
Disallow OTU editing in remote references

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#739]
#### Server
- [ ] return error response when edit attempted
- [ ] return error response when history reversion attempted

#### Client
- [x] hide all OTU editing components
- [x] hide reversion icon button in remote reference history views

**Comment by Miminko** [comment]
Are adding new OTUs and removing official ones allowed?

**Comment by igboyes** [comment]
- No
- Yes

The only thing that will be allowed is building an index.
