### ISSUE TITLE
Scrolling pagination

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#746]
- investigate possible implementations and determine if backend API changes are required
- remove `<PageHint />` component
- update the `<Pagination />` component to load more content on scroll

**Comment by Miminko** [comment]
Should the infinite list:
A) continuously add more elements to show to the end of the list as the user scrolls, thereby increasing the total number of rendered elements?
or
B) only show a fixed number of elements that get rendered as the user scrolls up and down?

**Comment by igboyes** [comment]
This is a technical decision that I think is yours to make.

I will say that A is far easier to implement, but of course it could lead to performance issues. However, it is unlikely that a user will scroll through more than 100 samples before either filtering the list down or clicking a list item.
