### ISSUE TITLE
Reference cloning UI update

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#749]
#### Add a select-type `<input />` to the cloning form to select the source reference

This will allow selection of a source reference if one was not preselected. The error _Target reference 
must be pre-selected in order to clone_ will not longer be necessary.

Clicking the clone icon button on an existing reference will preselect the correct select option.

#### Disable cloning when no other references are available.

In place of the form, show a message like _No source references available_ inside a panel. The clone button should be disabled too of course.

**Comment by Miminko** [comment]
Should references have unique names to avoid confusion for the selection input?

**Comment by igboyes** [comment]
Hmm. I'm not sure about that one. I will have to talk to Mike.

I was thinking, can you implement the selection in a `<ListGroup />` instead. Each item can then have have some more information along with the reference name (date, user, OTU count). This could deal with confusion by further differentiating the options.
