### ISSUE TITLE
Internal Control

### ISSUE THREAD

**Issue by Miminko** [virtool/virtool#764]
Currently, attempting to set a virus for the internal control of a reference results in a `PATCH http://localhost:9950/api/refs/:refId 404 (Not Found)`.

I think this is due to the fact that retrieving the available otu names returns a list of every available otu across references, rather than from otus that are specific to that particular reference. 

example:
`/api/refs/:refId/otus` correctly returns reference specific otu documents, but
`/api/refs/:refId/otus?names=true` returns names of all otus across all references

**Comment by igboyes** [comment]
Thanks. I'll check it out.
