### ISSUE TITLE
Reference export UI

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#774]
#### Implementation
Add user interface for exporting reference.

The button for doing this should be a menu-type icon next to the yellow pencil used for editing the reference.

A dropdown might be necessary for these as there are three possible ways to export the reference. The FontAwesome `ellipsis-v` would be a good icon for triggering visibilty of the dropdown.

I'll make it possible to download the entire reference in other formats as well, so the dropdown will leave room to expand into those options. Use a [header](https://react-bootstrap.github.io/components/dropdowns/#menu-items) labelled _Export_ above the three options for exporting: _Built_, _Unbuild_, _Unverified_.

#### API
The `v3` docs have been updated with the API method for exporting a reference.

**Comment by Miminko** [comment]
- do all references types (except blank created) allow for all three types of exports? (e.g. remote references?)
- currently get `GET http://localhost:9950/download/refs/:refId?scope=built 500 (Internal Server Error)`

**Comment by igboyes** [comment]
Yes. This should be fine unless you can think of some edge case I haven't considered. Using `unverified` with a remote reference will have the same effect as `unbuilt`.

Are you getting this Python error?: `Object of type 'datetime' is not JSON serializable`

https://sentry.io/share/issue/806b29d2ce244391aeca2242f61596ae/

I'll open an issue if so.

**Comment by Miminko** [comment]
Sorry, I forgot to restart the server.

It no longer gives an error, but does not initiate download. 
Does it require handling the response data in some way in the saga?
