### ISSUE TITLE
Reference card tweaks

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#786]
#### Latest Build
- link to the page for the index
- don't show the index id
- show _created at..._ as small subtext

#### Imported From
- show filename (`imported_from.name`)

#### Cloned from
- show source reference name (`cloned_from.name`)
- link to source reference using `cloned_from.id`

#### Remote From
- change to Remotes From
- make slug text a link to GitHub repo in a new tab (`target="_blank"` attribute)

**Comment by Miminko** [comment]
Cloned references seem to be missing the `cloned_from` field and information within their references.document entry.

**Comment by Miminko** [comment]
What sort of information should be included for imported files and source references?

**Comment by igboyes** [comment]
Created issue #790.

Updated main comment in this issue.
