### ISSUE TITLE
Strange upload disabling

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#794]
I am getting this strange `disabled` type styling on some uploads. The upload so still complete...

![image](https://user-images.githubusercontent.com/5943558/41130015-9ef67ba4-6a69-11e8-8050-e79c9c6f61e8.png)

**Comment by Miminko** [comment]
Should this fix be for the master branch?

**Comment by Miminko** [comment]
I created a PR for both branches to solve the upload ui issues

**Comment by igboyes** [comment]
Okay. Thanks. I will be merging to master and merging master in v3.
