### ISSUE TITLE
Render 404 components when details are not found

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#800]
From #798:
> should clone reference links to their source references have a check in place for cases where the source reference is deleted?

There are a number of other situations where there can be dead links with the Virtool client. I think the best way to deal with this is `404 Not found` pages. Problems to think about:

- how to handle `404` response from server in a consistent DRY way
- how to store `404` in Redux state
- may require change to current `null` / non-`null` method of waiting for async requests

**Comment by Miminko** [comment]
Should there only be 404 handling for pages that could be edited/removed by the user:
e.g. /otus/:otuId as opposed to pages that cannot be modified like /hmms/:hmmId ?
