### ISSUE TITLE
Force remote update check

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#815]
Allow checking for updated versions of remote references.
```
GET /api/refs/:id/update
```

Documentation is updated with this new enpoint. Suggest using circular `sync` [icon from FA5](https://fontawesome.com/icons?d=gallery&q=referesh). Show pending state with `<ClipLoader />`.

**Comment by Miminko** [comment]
@igboyes Should updating the `state.detail.remotes_from.last_checked` value be updated on the client side after the update check request response? or calculated server-side?

**Comment by igboyes** [comment]
The value should be retrieved from the server. In this case could we save a request by including the `last_checked` value in the update check request response?

If you think the value is not being updated, make sure you are running the latest server version because there was an issue with it not updating recently.

**Comment by Miminko** [comment]
I think it should save a request to get the specific reference again to update the `last_checked` value in `remotes_from` if it were included in the `release` object in the check updates response.

**Comment by igboyes** [comment]
I will implement this (#832).
