### ISSUE TITLE
Improve HMM purge UI

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#854]
Current state of affairs:
![image](https://user-images.githubusercontent.com/5943558/41381884-7db43012-6f1e-11e8-9212-04ab78a1755d.png)

- add `<ViewHeader />` with **HMM Settings**
- make purge button danger-styled
- wrap button with Alert or Panel with danger style with message:
  > Delete all HMM profile annotations and data files.
- make somewhat consistent with reference removal component

**Comment by Miminko** [comment]
Should the purge request be currently working? I seem to get a `DELETE http://localhost:9950/api/hmms 404 (Not Found)` error

**Comment by igboyes** [comment]
Yes. Are you definitely running the latest server?
