### ISSUE TITLE
Restarting Virtool fetch error

### ISSUE THREAD

**Issue by Miminko** [virtool/virtool#861]
Restarting, setting up, and saving virtool results in a fetch error:
```javascript
GET http://localhost:9950/setup/save 0 ()
Uncaught (in promise) TypeError: Failed to fetch
```
~It doesn't seem to affect anything in particular, the page reloads to the login page fine.~

sometimes can briefly see an error page
`Navigated to chrome-error://chromewebdata/`

**Comment by igboyes** [comment]
This error is occuring because there is no response for that request. It is probably not worth the effort to implement an error handler and test it.
