### ISSUE TITLE
Fix quick analysis functionality

### ISSUE THREAD

**Issue by Miminko** [virtool/virtool#871]
Currently the Quick Analyze feature for samples is not working since analyses require a reference id for an associated index.

**Comment by igboyes** [comment]
We do have to deal with this.

I'm thinking we should eliminate the quick analysis account settings:
![image](https://user-images.githubusercontent.com/5943558/41683102-89ffa7f0-748e-11e8-9542-f667b28183db.png)

When the user clicks the quick analyze icon on a sample, the dialog will always be shown and they will have to choose which references and algorithm to use.

This will kind of detract from the value of the quick analysis function. On way to make it better would be to allow users to perform this operation on multiple samples at once. Implementing multiple sample selection would make this possible. Check out #181.
