### ISSUE TITLE
Import / Clone reference

### ISSUE THREAD

**Issue by Miminko** [virtool/virtool#897]
Having some issues importing a reference, even on a fresh instance of virtool.
The [latest release](https://github.com/virtool/ref-plant-viruses/releases/tag/v0.1.2) from the **virtool / ref-plant-viruses** repository results in no server errors, but the import does not complete and instead stops on `progress: 0.99`, `step: load_file`.

This also seems to happen when cloning references as well. 
Remote references install ok, but cloning them stops on the `progress: 0.99`, `step: clone_otus`.

**Comment by igboyes** [comment]
Thanks. I will check it out.
