### ISSUE TITLE
Administrator administration

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#927]
In the users administration UI:
- add icon (and label?) indicating if a user is an administrator ([consider user-shield](https://fontawesome.com/icons/user-shield?style=solid))
- add input for changing user between a limited and administrative role

In the account UI:
- add similar label indicating if the account is an administrator

**Comment by Miminko** [comment]
Toggling from administrator to limited role for the currently logged in user can result in being denied access to the Administration > Users tab, therefore stuck as a limited user. 
`GET http://localhost:9950/api/users 403 (Forbidden)`

**Comment by igboyes** [comment]
Yes, admins should not be able to change their own roles. This should ensure that there is always at least one admin on the instance.

I will return an error from the API if this request is made (#937).
