### ISSUE TITLE
Missing sample locale fields

### ISSUE THREAD

**Issue by Miminko** [virtool/virtool#934]
A locale field can be submitted when creating samples, but locale entry is not displayed in sample detail, and currently cannot be edited via the edit sample UI

**Comment by igboyes** [comment]
Is it just not rendered? Or is it not included in the API response?

**Comment by Miminko** [comment]
Just the rendering is not implemented yet

**Comment by igboyes** [comment]
OK. I'll leave it to you.

**Comment by Miminko** [comment]
Should the sample detail page also list other information such as `srna: false`, subtraction host id and/or link to subtraction file?

**Comment by igboyes** [comment]
Yes, that's a good idea.

For the `srna` value, just replicate the creation form style (ie. Read Size = Normal || sRNA).

Link to subtraction page would be great.
