### ISSUE TITLE
Subtraction file size rendering

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#956]
File sizes aren't rendering correctly in the subtraction files view.
![image](https://user-images.githubusercontent.com/5943558/42351400-abd3c366-8069-11e8-8974-5b3704b898fd.png)

Sizes for sample files do render correctly. The JSON data for the subtraction files is there:
![image](https://user-images.githubusercontent.com/5943558/42351432-c7e883fc-8069-11e8-902b-8ef48cd859a1.png)

**Comment by Miminko** [comment]
I think this was fixed in PR #935

**Comment by Miminko** [comment]
I don't get the same JSON data as your screen shot, instead I get `size: {size: 121183084, modify: "2018-07-05T15:46:26.894000Z"}` object instead of a number

**Comment by igboyes** [comment]
No it should just be a number. Looks like a bug on my part. I'll check it out.
