### ISSUE TITLE
Change  depth from mean to median

### ISSUE THREAD

**Issue by MikeERott** [virtool/virtool#967]
In the latest version, read depth is calculated as a average, this can result in inflated read depth values due to very high single peaks in the readmapping. A median value may give a more realistic value of overall read depth.

**Comment by igboyes** [comment]
Can you do this @Miminko? Maybe it would be a good idea to have a toggle before we make median the only option.

**Comment by Miminko** [comment]
Sure!
Were you thinking to have a toggle for the depth display with 'mean' and 'median' as choices? 
And/or recalculate the averages after toggling the iqr to produce the trimmed data?

**Comment by igboyes** [comment]
Yes to the toggle. Maybe just two buttons. Don't put too much effort into it since I'm hoping we'll settle on one default method.

Is the IQR adjusted data used to calculate the mean depth? It didn't seem to be affecting the depth numbers when applied.

**Comment by Miminko** [comment]
The IQR is just for the chart display. The mean depth is calculated on the original data only.

**Comment by igboyes** [comment]
No, just base it of the original data for now.

We are going to have to play the IQR thing a bit because it is cutting the tops off of significant peaks.

**Comment by MikeERott** [comment]
Found this. Not sure if it is useful, applicable here.

Coverage uniformity can be expressed in various ways. IDT uses different methods to calculate coverage uniformity. The primary method, which is applicable to the widest range of applications, is to calculate the proportions of sequences that have greater than 0.2, 0.5, and 1.0 times the mean coverage.

**Comment by igboyes** [comment]
Made a new issue for fixing the IQR function: #974.
