### ISSUE TITLE
Data management in client

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#969]
The way API-sourced data is managed in the client needs to be improved.

For the purposes of this issue, we are talking only about the document-in-array type data usually stored in the `documents` property of a reducer.

#### More complete use of websocket messages
Instead of making `GET` requests when a websocket message indicates a change to the collection (eg. OTUs), use the message content to update the `documents` array.
- when an `insert` message arrives, insert the document in the message directly into the documents array
- when an `update` message arrives, update the document if it is already in the `documents` array, otherwise do nothing
- when a `remove` message arrives remove the document if it is already in the documents array
- consider cases where multiple `remove` messages might deplete the `documents` array to a point where it looks weird to the user

#### Don't `GET` unnecessarily when the user mounts a listing component (eg. `<OTUList />`
- once the initial `GET` request is made, the documents list should be kept updated via websocket messages
- develop method for checking if initial request has been made (`documents.length === 0` or dedicated property such as `fetched === true` maybe)

#### Search queries
- `GET` requests have to be made to satisfy this function
- think about caching previously found documents that don't match the query
- a caching functionality may be a bit more complicated so split into separate issue to get the rest of the work completed for merge ASAP

**Comment by Miminko** [comment]
- Websocket messages detailing OTU insert & update requires a `reference` field indicating which reference the particular otu is associated with.
