### ISSUE TITLE
Jobs view: multiple analysis not functioning

### ISSUE THREAD

**Issue by MikeERott** [virtool/virtool#971]
Under Jobs view, with multiple jobs in the que, only one job is shown running at any one time. Previous version of Virtool, at least 2 Pathoscope jobs would run in parallel. While running Pathoscope, it should also be possible to create a new sample at the same time, but this is no longer working either.

**Comment by igboyes** [comment]
This is due to unhandled `aiohttp` exceptions. These are for the most part due to bad connections between the Virtool server and GitHub (#763).

Aim to resolve #763 for `alpha.6` and see if the job scheduling issue persists.

**Comment by igboyes** [comment]
Sentry issue: [SERVER-HT](https://sentry.io/cph/server/issues/603247865/)

**Comment by igboyes** [comment]
Also may be caused by #1004.

**Comment by igboyes** [comment]
I think this should be resolved in the next update. Reopen if still having issues.
